### ISSUE TITLE
Logging the GQL request when using variable_values.

### ISSUE THREAD

**Issue by wmitchellUK** [graphql-python/gql#102]
I'm using version 2.0 and I'd like to add some logging in my app to show the log the full gql json complete with variables in a way that I can paste into GQL Playground for debugging purposes.

Any tips ?
     
    gql_statement = gql(gql_request.get_gql_template())

    result = client().execute(
    document=gql_statement,
    variable_values=request_params
    )

**Comment by leszekhanusz** [comment]
In GraphQL Playground, you would need to put the GraphQL query and the variables in separate places.

in the big left pane. You can put the query with:

```python
from graphql import print_ast

query_str = print_ast(gql_statement)
```

And in the bottom left pane, there is a "QUERY VARIABLES" where you can put the variables as a json payload. you can get it with:

```python
import json

variables_str = json.dumps(request_params)
```
