### ISSUE TITLE
compose queries like Apollo

### ISSUE THREAD

**Issue by japrogramer** [graphql-python/gql#103]
I have some mutations/queries that i want to compose into a single query/mutation.

for ex.
```
organization = """
mutation ( $organization: OrganizationInput!) {
  Organization: createOrfOrganization (details: $organization) {
    obj {
      id
    }
    status
    errors
  }
}
"""

taxonomy = """
mutation ($taxonomy: TaxonomyInput!) {
  Taxonomy: createOrfTaxonomy (details: $taxonomy) {
    obj {
      id
    }
    status
    errors
  }
}
"""
```

I would like to have a function that can take the code above and do something like this
```
>>> compose(organization, taxonomy)
mutation ( $organization: OrganizationInput!, $taxonomy: TaxonomyInput!) {
  Organization: createOrfOrganization (details: $organization) {
    obj {
      id
    }
    status
    errors
  }
  Taxonomy: createOrfTaxonomy (details: $taxonomy) {
    obj {
      id
    }
    status
    errors
  }
}
```

This is an important feature that the python code should support.

**Comment by KingDarBoja** [comment]
Hi @japrogramer 

For what I read at [apollo graphql](https://www.apollographql.com/docs/react/api/react-apollo/#configskip), they do make use of `compose` which comes from another package called [recompose](https://github.com/acdlite/recompose/blob/master/docs/API.md#compose) hence it is not a feature built-in graphql but more like a independent library.
