### ISSUE TITLE
Connection ack error when keep alive message arrives first

### ISSUE THREAD

**Issue by gregsanz182** [graphql-python/gql#108]
Hi!. Currently I'm using this package to test a Hasura project, but when the WebsocketsTransport waits for the ack message on initial connection, the Hasura server first responds with a keep alive message. Because of this, the WebsocketsTransport raises a TransportProtocolError exception, given that it waits for a `connection_ack`, not a `ka` message.

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sanchez/Projects/graphql_client.py", line 829, in test_subscription
    asyncio.run(self.something())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/sanchez/Projects/graphql_client.py", line 839, in something
    async with Client(
  File "/home/sanchez/Projects/venv/lib/python3.8/site-packages/gql/client.py", line 161, in __aenter__
    await self.transport.connect()
  File "/home/sanchez/Projects/venv/lib/python3.8/site-packages/gql/transport/websockets.py", line 508, in connect
    raise e
  File "/home/sanchez/Projects/venv/lib/python3.8/site-packages/gql/transport/websockets.py", line 503, in connect
    await self._send_init_message_and_wait_ack()
  File "/home/sanchez/Projects/venv/lib/python3.8/site-packages/gql/transport/websockets.py", line 193, in _send_init_message_and_wait_ack
    raise TransportProtocolError(
gql.transport.exceptions.TransportProtocolError: Websocket server did not return a connection ack
```

Here you can see the order from the messages sent by my Hasura server. In this case, I'm testing using the Hasura web console:

![image](https://user-images.githubusercontent.com/9099404/86171647-0dcf6d00-baeb-11ea-996a-1fabe09ba656.png)

As you can see, the `ka` message comes first, so TransportProtocolError rejects this message, and raises the above exception. Maybe TransportProtocolError needs to ignore `ka` messages when wating for ack message

**Comment by leszekhanusz** [comment]
Thank you for your bug report.
Could you please check that the PR #110 solves your problem ?

**Comment by hugbubby** [comment]
> Thank you for your bug report.
> Could you please check that the PR #110 solves your problem ?

How do you replace your local version of gql in a python venv with the version from this pull request?

**Comment by KingDarBoja** [comment]
Not well versed on webscokets but as far as I know, it uses TCP (Transmission Control Protocol) which is the one that sends the `Keep-Alive` messages and is causing this issue. A good resource to understand for anyone willing to learn is [appsync-websockets-python](https://aws.amazon.com/blogs/mobile/appsync-websockets-python/) (from AWS).

Reviewing right now the linked PR, this should be release with the next beta version.

**Comment by leszekhanusz** [comment]
Websockets are indeed done on top of TCP.
What may be confusing is that there is two types of keep alive at different levels of the network model.

The Keep-Alive in the transport level are managed by the TCP stack of the operating system. We don't see them in our code.

The keep alive we are talking about here are simply message exchanged in the application level. This is an optional feature of the different GraphQL servers.
