### ISSUE TITLE
Latest commit not released - https://github.com/graphql-python/gql/commit/82577773d5965d139985cd5756b2a1929131850b

### ISSUE THREAD

**Issue by Xotabu4** [graphql-python/gql#11]
Hi!
I noticed that pip version of this lib do not contain latest commit with 'cookies' param for transport.
https://github.com/graphql-python/gql/commit/82577773d5965d139985cd5756b2a1929131850b

Could you please release lib to pip properly, to not grab code directly from github?

**Comment by Cito** [comment]
This is available in v0.2.0 und v0.3.0 now.
