### ISSUE TITLE
Cannot run tutorial in jupyter 

### ISSUE THREAD

**Issue by dmagas-auto1** [graphql-python/gql#115]
I did `pip install --pre gql` in a fresh conda env, run basic usage from the example and got:
```---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-10-f10649e5cacb> in <module>
     20 
     21 # Execute the query on the transport
---> 22 result = client.execute(query)
     23 print(result)

~/anaconda3/lib/python3.7/site-packages/gql/client.py in execute(self, document, *args, **kwargs)
    114 
    115             assert not loop.is_running(), (
--> 116                 "Cannot run client.execute if an asyncio loop is running."
    117                 " Use execute_async instead."
    118             )

AssertionError: Cannot run client.execute if an asyncio loop is running. Use execute_async instead. 
```

Running it in pure python in the console works.

**Comment by leszekhanusz** [comment]
It is not possible to run execute or subscribe on the client directly if you already have an asyncio loop already running.
In that case you could either use the `await client.execute_async(...) `or you should use:
```python
async with client as session:
    session.execute(...)
```

as described in the [async usage section](https://github.com/graphql-python/gql#async-usage-with-asyncio)

**Comment by leszekhanusz** [comment]
I added a warning note below the basic example to warn users of this problem (#116)
