### ISSUE TITLE
Run multiple mutations in one request

### ISSUE THREAD

**Issue by Felix-N** [graphql-python/gql#119]
Hi,

how do you run multiple mutations in one request?

I've found the option to pass an operation_name into execute, but that only executes that one operation.

**Comment by leszekhanusz** [comment]
You can put multiple operations in a single mutation, there is no need to specify an operation_name.
See [multiple mutations on hasura for example](https://hasura.io/docs/1.0/graphql/manual/mutations/multiple-mutations.html)

**Comment by gyscos** [comment]
The problem is that currently, if any mutation fails, then an exception is still raised. Other mutations may have succeeded, and a `data` field may be present in the response, but it will be ignored.

**Comment by leszekhanusz** [comment]
> A solution may be to include data in the returned exception, so users can decide to check it for whatever worked.

That is a good idea!

**Comment by leszekhanusz** [comment]
@gyscos is this PR ok for you ?

**Comment by gyscos** [comment]
Looks good to me, thanks!

**Comment by leszekhanusz** [comment]
This is now possible in version 3.0.0a2
