### ISSUE TITLE
What do you recommend for transport middlewares?

### ISSUE THREAD

**Issue by sneko** [graphql-python/gql#120]
Hi,

I'm trying to apply some request patching on each request and from what I see in the code it's not possible.

I can for sure do this:
```
http_client.transport.headers = { ... }
```
to customise the headers.

But I have no way to add a proper middleware specific to each request. To put some context, if you use authentication token valid for X hours, you can use the above method with almost no risk at all.

But in my case I sign with a private key the content of the request, so each request needs its own signature. So by setting a shared variable like `self.http_client.transport.headers` I take the risk for 2 concurrent requests that the "first one" will use the token of the second request if they are in different threads.

Do you know if that's on the roadmap to add transport middlewares? Or do you have any advice how I could simply wrap your Transport object with my logic (with lockers/mutexes...)?

Thank you,

cc @leszekhanusz @Cito

**Comment by leszekhanusz** [comment]
If you use different threads, then you could maybe use a different transport and client instance for each thread. The http headers are sent only at the beginning of the connection anyway so a new connection is needed each time.

or if you control the backend, then you could put the token as a variable in your GraphQL schema ?

**Comment by sneko** [comment]
@leszekhanusz indeed for different threads it may be better to manage different clients than playing with lockers... Otherwise with `asyncio` I guess since that's in 1 thread and it gives the hand to other instructions when an `await` is reached I could do each time:
```
# Request 1
payload = { ... }
self.prepare_my_headers(payload)
await self.get_XXX_from_backend(payload)

# Request 2
payload = { ... }
self.prepare_my_headers(payload)
await self.get_YYY_from_backend(payload)
```
_Note: I pass the payload to prepare headers since I need to sign it_

It seems a bit redundant but like that I make the headers settings are linked to used payload.

Another solution would be to extend the HTTPTransport session. What do you think?

By the way when you say:


> The http headers are sent only at the beginning of the connection anyway so a new connection is needed each time.

I'm not sure to fully understand. Do you mean I need to manage a
```
http_transport.connect()
```
before each of my request done with `.execute()` so the headers get sent?

It seems a bit cumbersome, that's why I have a doubt hmmm...

**Comment by leszekhanusz** [comment]
> I'm not sure to fully understand
Sorry, my fault, I got confused and thought about the websockets transport and not the http transport, you don't need to do anything, the connect is done automatically.

So If you are not using threads and you need different headers, for connections which are running concurrently using asyncio, with the http transport, then I don't think there will be any problem if you set the headers manually before each connection. Asyncio is not like threads where the execution flow can be interrupted between two random lines of code.

The connect method of AIOHTTPTransport is synchronous (this is not the case for the websockets transport)

**Comment by sneko** [comment]
I will go this way 👍 

Thank you @leszekhanusz 😀
