### ISSUE TITLE
Is there documentation besides the README?

### ISSUE THREAD

**Issue by penyuan** [graphql-python/gql#122]
Thanks for creating and maintaining this useful library!

As a newcomer, I would like to ask if there is more comprehensive documentation for this library besides the README file in this repository? Similarly is there documentation on this library's API/callable objects, etc.? The current README seems to only cover a fraction of this library's functionality and I'd love to learn more!

**Comment by KingDarBoja** [comment]
Hi @penyuan 

Please take a look at #117 which is the first step towards bringing the entire documentation into a hosted website so any developer can take a look at the internal API.

🚀  Cheers!

**Comment by penyuan** [comment]
> Please take a look at #117 which is the first step towards bringing the entire documentation into a hosted website so any developer can take a look at the internal API.

Oh I see. Thank you! I will subscribe to pull request #117. Hope it will be merged soon so that I can more easily learn. :smile:

**Comment by KingDarBoja** [comment]
The new docs are available at https://gql.readthedocs.io/en/latest/ 🚀
