### ISSUE TITLE
Error on parsing GraqphQL query with null

### ISSUE THREAD

**Issue by ayuryshev** [graphql-python/gql#129]
What I'm try to do:

```python
import gql
gql('''
mutation {
  update_document(_set: {checksum: null}, where: {checksum: {_is_null: false}}) {
    returning {
      id
    }
  }
}''')
```

That's a correct mutation that works in hasura UI (which is built on graphiql)
And it works in graphql-dotnet.

I found that similar problem was in apollo-graphql:  https://github.com/apollographql/graphql-tag/issues/47
And it was solved with graphql-tag@1.3.0

I suppose that's a bug

Pipfile.lock:

```json
   "gql": {
            "hashes": [
                "sha256:35032ddd4bfe6b8f3169f806b022168932385d751eacc5c5f7122e0b3f4d6b88",
                "sha256:fe8d3a08047f77362ddfcfddba7cae377da2dd66f5e61c59820419c9283d4fb5"
            ],
            "index": "pypi",
            "version": "==2.0.0"
        },
```

**Comment by leszekhanusz** [comment]
Could you please try it with the latest preliminary version (v3.0.0a1) ?

**Comment by ayuryshev** [comment]
OK
```python
import gql

gql.gql('''
mutation {
  update_document(_set: {checksum: null}, where: {checksum: {_is_null: false}}) {
    returning {
      id
    }
  }
}''')
```

No exceptions during parsing.
I see that `__repr__` of query changed (I suppose)

Testing if it works

**Comment by ayuryshev** [comment]
I can confirm that with v3.0.0a1 - everything works as expected.

So IMO:
- it deserves to be mentioned in documentation
- and then could be closed

**Comment by KingDarBoja** [comment]
This is probably caused by how underlying `graphql-core` changed the way it handles null values on GraphQL queries, which should match the current spec, hence the reason why it works on `gql v3.0.0.a1`.
