### ISSUE TITLE
Skip https certificate verification 

### ISSUE THREAD

**Issue by omph** [graphql-python/gql#14]
Hi,

It seems it's not possible to skip https certificate verification without hardcode in the lib.

Skip works fine if to add in:
class RequestsHTTPTransport() -> execute: post_args -> add 'verify': False

And it seem's it would be perfect to add https verification as  additional method's param.

**Comment by scjody** [comment]
Note that https://github.com/graphql-python/gql/pull/45 can be used to fix this issue.
