### ISSUE TITLE
RPM library available ?

### ISSUE THREAD

**Issue by sreerajkksd** [graphql-python/gql#140]
This is more of a request than an issue.

Is it possible to have an rpm library for this package ?

**Comment by KingDarBoja** [comment]
I have zero knowledge about rpm packaging so maybe someone who does should support it.

It seems to be used by several linux distributions and the google search gives this https://docs.python.org/2.0/dist/creating-rpms.html as first result.

**Comment by leszekhanusz** [comment]
Sorry, this is not really the responsibility of a python package maintainer to create rpms. You should put a ticket in your specific distribution issue tracker. And they should probably wait that the stable 3.0 version is released IMHO.
Thanks @KingDarBoja for the link.
