### ISSUE TITLE
How to handle websocket disconnects?

### ISSUE THREAD

**Issue by sneko** [graphql-python/gql#144]
Hi @leszekhanusz ,

Do you have any recommended way to handle disconnection of websockets?

Let's say in my case I:
1. init the websocket transport and connect
2. in different tasks: subscribe to different GQL subscriptions
3. launch my main program loop (business stuff)

In other languages (e.g. Golang, Javascript), in case the websocket is lost, I can handle the error in a callback and just force the websocket transport to reconnect (and it's automatically resubscribing to the same ones than already subscribed before being disconnected).

In this Python library I don't know how I could handle this case?

Thank you,

**Comment by leszekhanusz** [comment]
Hi,

You can use the backoff module.
This is explained in the gql docs [here](https://gql.readthedocs.io/en/latest/advanced/async_advanced_usage.html)

**Comment by sneko** [comment]
I used backoff module for different things but probably didn't see this part. Sorry! Will give it a try in following weeks :) 

Thank you!
