### ISSUE TITLE
Add GitHub action to test gql on windows

### ISSUE THREAD

**Issue by leszekhanusz** [graphql-python/gql#146]
It happened multiple times already that the test suite is working well under Linux but it fails under Windows.

I think it should be possible to add a GitHub action to test GQL under windows automatically for each push.

**Comment by KingDarBoja** [comment]
No worries, easier to add 🚀 Should be another build setup for windows only and a specific python version to avoid repeating the results. See: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

**Comment by KingDarBoja** [comment]
Fixed by #152
