### ISSUE TITLE
Optional dependencies for transports

### ISSUE THREAD

**Issue by leszekhanusz** [graphql-python/gql#147]
Currently, the latest version installs all the dependencies necessary for all the underlying transports:

* requests
* websockets
* aiohttp

It should be possible to install gql without all the dependencies if we only use one transport!

My first idea was to try that by default, all the dependencies are added, but that it could be possible to remove dependencies if you only need one transport.

Apparently [this is not possible](https://github.com/pypa/setuptools/issues/1139)

Please comment if you have an idea.

**Comment by nihaals** [comment]
Why not make it required to include an extra when installing the package? I don't think this is necessarily a bad thing and you would know you are missing a dependency when you attempted to import a transport (each transport should probably be separated into their own file to make sure the transport-only dependencies are only required for their class). In many cases users could even use transports like `requests` without including the extra as it's such a common dependency (although it should be documented that using the extra is still recommended in case another dependency is added for a specific transport)

**Comment by leszekhanusz** [comment]
OK, that's what we are going to do. I made this issue to see if someone had a better idea for this.

**Comment by leszekhanusz** [comment]
Implemented in release v3.0.0a4
