### ISSUE TITLE
HTTPX Transport

### ISSUE THREAD

**Issue by nihaals** [graphql-python/gql#154]
[HTTPX](https://www.python-httpx.org) is a HTTP library for Python which supports both sync and async requests. A big advantage of HTTPX is that it supports Trio (as well as asyncio), something not available with the current AIOHTTP Transport

**Comment by KingDarBoja** [comment]
The important part is documented at https://www.python-httpx.org/async/#supported-async-environments

Would be great to include another transport that make use of Trio, however I am a bit worried by the amount of packages being installed to use this library as stated at #147.

**Comment by nihaals** [comment]
Should this be marked as blocked by #147? I do agree that this issue should be solved first but it shouldn't be too hard to find a solution

**Comment by KingDarBoja** [comment]
No need to be blocked, this can be added into the library and later see if we can solve the optional dependencies.
