### ISSUE TITLE
Getting "zsh: no matches found: gql[all]" in zsh shell

### ISSUE THREAD

**Issue by rkpatel33** [graphql-python/gql#168]
I don't know why, but I seem to get this error message when I try to install the library when I am in a `zsh` shell.

```
 $ pip install --pre gql[all]
zsh: no matches found: gql[all]
```

![image](https://user-images.githubusercontent.com/3799489/98428285-a6f03080-2055-11eb-8108-9086b1755a93.png)

Not sure why. If I start a `bash` shell it seems to work ok. Any ideas here? I realize this not related to the library itself, so apologies in advance if this is the wrong place for it.

What I am really trying to do is install the full package with all dependencies using `pipenv`but this Pipfile keeps installing 2.0.

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
autopep8 = "*"
flake8 = "*"

[packages]
dash = "1.17.0"
gql = "v3.0.0a4"
ipykernel = "*"
jupyterlab = "*"
pandas = "1.1.3"
pytz = "*"
requests = "*"

[requires]
python_version = "3.6"

[pipenv]
allow_prereleases = true
```

**Comment by leszekhanusz** [comment]
Apparently zsh uses square brackets for pattern matching so you need to escape the command.

See [this answer on stackoverflow](https://stackoverflow.com/a/30539963/1221252)

So you could try something like this:

```
pip install --pre 'gql[all]'
```
