### ISSUE TITLE
How to dynamic values to the queries

### ISSUE THREAD

**Issue by jagadish432** [graphql-python/gql#171]
How to pass the dynamic values when calling gql queries like below.

```
query = gql('''
      query GetCountry($id: ID!) {
  getCountry(id: $id) {
    id
    countryID
    metadata
    received
    modified
    owner
  }
}
    ''')
```

so, if this is the query, then how to pass the dynamic countryID value to gql client ??

**Comment by leszekhanusz** [comment]
Use the [variable_values argument](https://gql.readthedocs.io/en/latest/usage/variables.html)

**Comment by jagadish432** [comment]
my bad !! I forgot to reply. Apologies.

It's working, thanks for pointing me to the correct docs.
