### ISSUE TITLE
Make a release that includes the fix for validation of default enum values

### ISSUE THREAD

**Issue by leoyvens** [graphql-python/gql#180]
I believe the fix of https://github.com/graphql-python/graphql-core/issues/111 is needed for queries that rely on default enum values to be correctly validated. If you could kindly release a version of this package that includes that fix, that would be much appreciated.

**Comment by leszekhanusz** [comment]
We would need a new release of graphql-core first.

**Comment by LefterisJP** [comment]
We (https://github.com/rotki/rotki) would love to see a fix for this. We ran into this last night. I understand it's blocked until a new release of graphql-core is ready. Let us know if we can do anything to push it forward.

**Comment by leszekhanusz** [comment]
This should be fixed by installing the graphql-core version 3.1.3
No new release of gql is needed as this fits the gql dependencies (graphql-core>=3.1,<3.2)

Thanks @Cito

**Comment by LefterisJP** [comment]
Thanks guys. We will try it.
