### ISSUE TITLE
Customizable ExecutionResult, or how to get other API response parts

### ISSUE THREAD

**Issue by extrin** [graphql-python/gql#188]
https://github.com/graphql-python/gql/blob/459d5ebacce95c817effcd18be152d6cf360cf2b/gql/transport/requests.py#L174
### Case:
The GraphQL API that I need to make requests to, responds with some other useful information, except of `data` block:
```json
{
    "data": {...},
    "extensions": {
        "pageInfo": {
            "limitPage": 200,
            "totalCount": 23306516,
            "hasNextPage": true,
            "lastId": 41922710
        }
    }
}
```
But, as **gql** transport composes `ExecutionResult` from `data` and `errors` blocks only, I'm not able to get and use the `extensions` part in my code. 
I was hoping to use `hasNextPage` and `lastId` values to iterate through pages of data, to load all the data to database. 
### Question:
Is there any way to get `extensions` part of response, along with `data` and `errors`, using **gql**?

**Comment by leszekhanusz** [comment]
Currently this is not possible, the `execute` and `subscribe` methods of the session only return the data or throw an error and as you noticed, the ExecutionResult instance is not created with the possible extensions field in the transports.

If you want direct access to the ExecutionResult instance, you could use the `_execute` and `_subscribe` methods of the session.

A simple PR could be made to add the extensions field of the ExecutionResult object for all the transports.

**Comment by KingDarBoja** [comment]
AFAIK the execution result only returns the `data` and `errors` fields according to the official spec and js implementation: https://graphql.org/graphql-js/execution/#execute

So no clue how that graphql-API is returning such extensions.

**Comment by extrin** [comment]
Thanks for your answers!
I see that the extensions field [was added](https://github.com/graphql-python/graphql-core/commit/3359fe60d9940b174270426438a89d629b6cc6e2) to ExecutionResult in graphql-core. 
It seems that this change is not in release version yet. I just tried to fork repo and add extensions field for transports, but the ExecutionResult imported from graphql doesn't have this field either.

**Comment by dkbarn** [comment]
> A simple PR could be made to add the extensions field of the ExecutionResult object for all the transports.

Even if "extensions" was added to the ExecutionResult object for all transports, it would not be retrievable using Client.execute, because that method returns a Dict object containing only the contents of the "data" key: https://github.com/graphql-python/gql/blob/master/gql/client.py#L420

**Comment by KingDarBoja** [comment]
This should be fixed by #190

**Comment by leszekhanusz** [comment]
> Even if "extensions" was added to the ExecutionResult object for all transports, it would not be retrievable using Client.execute, because that method returns a Dict object containing only the contents of the "data" key: https://github.com/graphql-python/gql/blob/master/gql/client.py#L420

What we could maybe do, is to add an argument to the execute method to specify a key which will be inserted inside the data Dict.

```python

    async def execute(self, document: DocumentNode, extensions_key: Optional[str] = None, *args, **kwargs) -> Dict:

        ....

        if result.extensions is not None and extensions_key is not None:
            result.data[extensions_key] = result.extensions

        return result.data
```

**Comment by leszekhanusz** [comment]
Finally I choose to add a `get_execution_result` argument to `execute` and subscribe `methods`.

See PR #257
