### ISSUE TITLE
gql 3.x.y not available as python-poetry dependency

### ISSUE THREAD

**Issue by deedf** [graphql-python/gql#189]
Versions 2.x.y are available as dependencies for python-poetry, but no version 3.x.y is.

Extremely annoying for users of python-poetry, especially since docs for versions 2.x.y are apparently nowhere to be found.

**Comment by leszekhanusz** [comment]
Version 3 is still a prerelease.
Did you try the [--allow-prereleases flag of poetry ?](https://github.com/python-poetry/poetry/issues/1665)

**Comment by deedf** [comment]
I did not know about it, thanks. It's weird that it doesn't seem to be supported by 'poetry search', only 'poetry add' apparently.
