### ISSUE TITLE
Failed to get entities from store: canceling statement due to conflict with recover

### ISSUE THREAD

**Issue by smatiush** [graphql-python/gql#191]
hi,
I'm trying to do a time-traveler query, to retrieve some info from a contract in ethereum blockchain.
i need to retrieve the historical state of that contract, to achieving this i run a `while len(results_query["swaps"]) > 0:`,
at every iteration the last block get fetched from the query and added to the next query(string and after the modification passed to `gql()`,function of the lib)that need to be executed.
after 2580 row, the function `result = await self.session.execute(query)` raise an error `Failed to get entities from store: canceling statement due to conflict with recovery`.
I'm asking for some explanation of the error or some troubleshooting technics.
thanks, have a good day

QUERY: ```query trades($blockNum: Int=11814699)
                                    {
                                    swaps(where:{pair: "0xa478c2975ab1ea89e8196811f51a7b7ade33eb11"}, 
                                    orderBy: timestamp, 
                                    orderDirection: desc,
                                    first:15, 
                                    block: {number:$blockNum}) {
                                    id
                                    timestamp
                                    amount0In
                                    amount1In
                                    amount0Out
                                    amount1Out
                                    }
                                    transaction {
                                      blockNumber
                                    }
                                  }
                                }```

**Comment by leszekhanusz** [comment]
Your problem is with the backend, not the gql client.

You can see the messages exchanged from the client to the server using [logging](https://gql.readthedocs.io/en/v3.0.0a5/advanced/logging.html) if you want to debug.

**Comment by smatiush** [comment]
ok thx i will contact the CS of my subgraph
