### ISSUE TITLE
gql transport that communicates directly with WSGI/ASGI app

### ISSUE THREAD

**Issue by dkbarn** [graphql-python/gql#192]
For the purposes of writing tests for my graphql server, I'd like the ability to communicate directly with the WSGI App object, rather than have to set up a local web server and go through one of gql's transport layers in each test.

I know that gql already provides the ability to interface with a local GraphQLSchema, but this then bypasses the the WSGI layer, which is where the graphql framework (in my case, ariadne) builds an executable schema and associates types with resolvers.

Is it possible for a gql client to communicate with a WSGI/ASGI object?

**Comment by leszekhanusz** [comment]
Why is this a problem to set up a local server for each test? Is it not fast enough?

You can run the gql client in a separate Thread, like in this [test](https://github.com/graphql-python/gql/blob/459d5ebacce95c817effcd18be152d6cf360cf2b/tests/test_requests.py#L35)

**Comment by dkbarn** [comment]
Speed is kind of an issue, but it's more that it's just awkward to have to host a local web server as part of your tests. Especially if your tests are run as part of an automated CI/CD system on some other machine. Creating a web server involves taking up a port, which means you have to worry about concurrency or come up with dynamic assignment of that port.

Most web frameworks provide a test client for convenience.

Django provides django.test.Client: https://docs.djangoproject.com/en/3.1/topics/testing/tools/#overview-and-a-quick-example
Falcon provides falcon.testing.TestClient: https://falcon.readthedocs.io/en/stable/api/testing.html#falcon.testing.TestClient
Flask uses werzeug.test.Client: https://werkzeug.palletsprojects.com/en/1.0.x/test/#werkzeug.test.Client

None of these test clients require a web server to be running -- they all connect directly with the WSGI application.

In the end I was able to fulfill my own need by writing a custom Transport class which was very similar to the RequestsHTTPTransport, but made calls to falcon's simulate_request rather than use the real requests library.

But I still think it could be beneficial for gql to have a WSGITransport class to meet this need in a more generic way.

**Comment by leszekhanusz** [comment]
Hi,
As you've been able to solve your problem by creating your own transport, I would like to close this issue.

**Comment by ktmud** [comment]
This should now be possible with the addition of [httpx transport](https://github.com/graphql-python/gql/pull/370) [[doc](https://gql.readthedocs.io/en/latest/modules/transport_httpx.html)].

```python
from gql import Client, gql
from gql.transport.httpx import HTTPXTransport

from my_app import app

transport = HTTPXTransport(url="https://test_app/", app=app)

client = Client(transport=transport, fetch_schema_from_transport=True)

query = gql(
    """
    query getContinents {
      continents {
        code
        name
      }
    }
"""
)

result = client.execute(query)
print(result)
```

**Comment by dkbarn** [comment]
@ktmud it's not clear to me how your example code actually bypasses HTTP. You are specifying an https:// url in the creation of HTTPXTransport, so presumably this would still require hosting a web server in order to work. Is the "url" kwarg optional? Can you supply HTTPXTransport with only the "app" kwarg?

**Comment by ktmud** [comment]
It's handled by httpx: https://www.python-httpx.org/advanced/#calling-into-python-web-apps

The `url` and its schema doesn't matter. You can use anything that you app would recognize.
