### ISSUE TITLE
Parser raises an error for null Boolean Type

### ISSUE THREAD

**Issue by DeanArbel** [graphql-python/gql#196]
Following a [commit](https://github.com/octokit/graphql-schema/commit/18c40d2bb68d8f27acfc62e768d34aadfca9e8b2#diff-9fcde326d127f74194f70e563bdf2c118c51b719c308f015b8eb0204a9a552fb) GitHub introduced to their schema yesterday `gql` can no longer parse its schema, as it fails on this `null` `Boolean` type:

```
{'name': 'isVerified', 'description': 'Filter by if the domain is verified.', 'type': {'kind': 'SCALAR', 'name': 'Boolean', 'ofType': None}, 'defaultValue': 'null'}
```

GitHub claims this change is in accordance with the [GraphQL standards documentation](https://graphql.org/graphql-js/basic-types/):

> By default, every type is nullable - it's legitimate to return null as any of the scalar types. Use an exclamation point to indicate a type cannot be nullable, so String! is a non-nullable string.

> Therefore, it appears that a null default value for a boolean is valid in GraphQL.

Currently the code specifically ignores `null` values.

![image](https://user-images.githubusercontent.com/20818773/109168192-3d706b00-7787-11eb-8594-d84361c4081a.png)

**Comment by leszekhanusz** [comment]
The default value is the null string instead of null ?

**Comment by DeanArbel** [comment]
Yeah, that's correct.

**Comment by leszekhanusz** [comment]
Yep, anyway it is graphql-core which is parsing the schema so you should create an issue [there](https://github.com/graphql-python/graphql-core/issues)

**Comment by DeanArbel** [comment]
@leszekhanusz I see that the issue actually originates from the `graphql-core-legacy`, in this line: https://github.com/graphql-python/graphql-core-legacy/blob/master/graphql/language/parser.py#L502.

Why is `gql` using the `legacy` version of `graphql-core`?

**Comment by leszekhanusz** [comment]
You probably don't have the latest gql version. Please check the documentation to install the latest pre-release version of gql.

**Comment by DeanArbel** [comment]
@leszekhanusz You're right, I will start using the pre-release version of gql, as it seems to solve the issue.
