### ISSUE TITLE
 ModuleNotFoundError: No module named 'gql.transport.aiohttp'

### ISSUE THREAD

**Issue by LeGeRyChEeSe** [graphql-python/gql#199]
hello i've this issue `ModuleNotFoundError: No module named 'gql.transport.aiohttp'` when i try to run my script,
i already installed this package with `python3 -m pip install aiohttp gql` but it does nothing. Thx in advance.

I'm on raspbian

**Comment by KingDarBoja** [comment]
You need to install the extra dependencies to use the corresponding transport, checkout [gql docs - less dependencies](https://gql.readthedocs.io/en/latest/intro.html#less-dependencies) section 😉 

In your case, you need to run `pip install --pre gql[aiohttp]`

**Comment by nickjm** [comment]
I get `gql 2.0.0 does not provide the extra 'aiohttp'` when running this

**Comment by KingDarBoja** [comment]
> I get `gql 2.0.0 does not provide the extra 'aiohttp'` when running this

You need to install the pre-release version by using `--pre` flag as shown in my previous comment. Cheers!

**Comment by nickjm** [comment]
@KingDarBoja FYI I think if you install 2.0 beforehand you have to completely uninstall for this to work. Might help others who accidentally did a non `--pre` at some point

**Comment by ihjrlosangeles** [comment]
no matches found: gql[aiohttp]

**Comment by levimake** [comment]
no matches found: gql[aiohttp]
