### ISSUE TITLE
Any plan for handling "ka" (keep-alive) and ping-pong checks?

### ISSUE THREAD

**Issue by sneko** [graphql-python/gql#200]
Hi @leszekhanusz ,

I'm wondering if there is any plan to support the keep-alive message? It comes from the server to make sure the connection is still alive, and if the client receives no KA within a specific timeout defined, it behaves as the connection was lost.

When seeing:
https://github.com/graphql-python/gql/blob/d7d871f89436a5cda05fda89319476117dbb73ca/gql/transport/websockets.py#L186
and:
https://github.com/graphql-python/gql/blob/d7d871f89436a5cda05fda89319476117dbb73ca/gql/transport/websockets.py#L316

I understand that's not implemented, but just wondering if it's in the pipe.

Also, in the same kind of standards, Keep-Alive makes sure the client will react in case of lost connection, but on it's end the server won't know if the connection was lost (router shut down for example, or loss of connectivity, that are not proper terminations). This is usually handled for websockets by an end-to-end "ping-pong" protocol between the client and the server:
* The server sends a "ping" every X interval
* The client has to reply "pong" within a timeout defined otherwise the server considers the connection as lost (which help freeing memory and doing specific stuff like updating client status in the database...)

Is it also something on your plan? It would definitely help.

Thank you,

**Comment by sneko** [comment]
@leszekhanusz I'm almost done with implementing the keep-alive part. I will do a PR tomorrow.

I hope to finish receiving a ping from the server and sending back the pong.

Also, I'm not that familiar with Python tests and I'm not sure how to proceed. For now I'm testing with real software... After PRs I would be glad if you could take a look to see how new tests could fit the commits.

**Comment by leszekhanusz** [comment]
Hi @sneko

You are right, it could be a good idea to implement closing the connection if we don't receive a keep-alive message.
We could add a `keep_alive_timeout` argument to the `__init__` method of `WebsocketsTransport`which is None by default (Keep Alives are just ignored as it is now) and if we don't receive a keep alive during this time raise a TimeoutError.

On the other hand, the client should never send something in response because the `WebsocketsTransport` transport should follow the [specification](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md)

Any deviation from this protocol should be done in a custom class created by the user.

**Comment by sneko** [comment]
> On the other hand, the client should never send something in response because the WebsocketsTransport transport should follow the specification

@leszekhanusz I guess for the second paragraph you meant about the `ping-pong` pattern.

For evolutivity I'm wondering if that's a good thing to extend the `WebsocketsTransport`, because in the future it would imply multiple levels of inheritance if things like that appear.

Maybe it would be better to add like a "middleware" pattern when processing the receive content? And from `WebsocketsTransport` inside `self._handle_answer` I would have just to loop over middlewares added by the developer, through something like `self.add_before_receive_middleware(func)`.

What do you think?

**Comment by sneko** [comment]
@leszekhanusz after reading dozen of posts, I guess things need to be discussed... I gave more links/insights at the library repo you use: https://github.com/aaugustin/websockets/issues/928 feel free to comment 😄
