### ISSUE TITLE
[Question] Is there any documentation about error handling?

### ISSUE THREAD

**Issue by felinto-dev** [graphql-python/gql#204]
Hello!

Is there any documentation about error handling?

```py
        try:
            client.execute(query, variable_values=params)
        except:
            pass
```

I want to catch the error of when the GraphQL endpoint returns the error code 400 - 403, and **NOT** an error related to the incorrect schema, for example.

I would know what NameError I should assign to except block to be able to print error messages in a friendly way to the user.

**Comment by leszekhanusz** [comment]
This is not really documented except maybe in the [source code](https://github.com/graphql-python/gql/blob/master/gql/transport/exceptions.py)
You can check [this comment](https://github.com/graphql-python/gql/pull/195#issuecomment-826071975) explaining the situation.

A 40x error should normally generate a TransportServerError and will in the next release put the http code in the TransportServerError exception.
