### ISSUE TITLE
Incorrect typing of variable_values

### ISSUE THREAD

**Issue by markedwards** [graphql-python/gql#205]
In `AIOHTTPTransport.execute` and `AsyncTransport.execute`, `variable_values` is typed as `Optional[Dict[str, str]]`.  GraphQL variable objects are not limited to string values, so this typing is not right.

The typing used in `RequestTransport.execute` is more appropriate (`Optional[Dict[str, Any]]`).

Happy to submit a PR.

**Comment by leszekhanusz** [comment]
Indeed, well spotted.
Feel free to submit a PR.
