### ISSUE TITLE
gql-cli pagination

### ISSUE THREAD

**Issue by abitrolly** [graphql-python/gql#206]
Looks like https://gql.readthedocs.io/en/latest/gql-cli/intro.html doesn't support pagination, which is necessary to get all results from API calls like GitLab https://docs.gitlab.com/ee/api/graphql/getting_started.html#pagination in one go.

Are there any plans to add it?

**Comment by inesusvet** [comment]
Could you please provide an example of the query, variables and the gql usage for this API call

**Comment by abitrolly** [comment]
That should work for a query. The project https://gitlab.com/gitlab-org/growth/product/-/issues contains about 500 issues and it should not run over API requests limits if executed several times.
```
query {
  project(fullPath: "gitlab-org/growth/product") {
    name
    issues {
      edges {
        node {
          title
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
```
Variables:
- the name of the project
- command line flag `--pages` to tell that pagination should be used
  - --pages=all - all pages

Not sure if the number of pages should start with 0 or 1. :D

**Comment by abitrolly** [comment]
Workspace setup.
```
git clone https://github.com/graphql-python/gql
cd qgl
pipenv install -e .
```

**Comment by leszekhanusz** [comment]
Pagination can be different for each type of schema, so it will not be implemented in gql-cli which should be generic for all types of schemas.

But you can modify your query to add variables and pass variables from the command line. Like this:

```
echo '
query getIssues ($first: Int, $after: String) {
  project(fullPath: "gitlab-org/growth/product") {
    name
    issues (first: $first, after: $after) {
      nodes {
        title
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
' > issues.gql
cat issues.gql | gql-cli https://gitlab.com/api/graphql --variables first:2 after:eyJpZCI6IjgwNDc5NDc3IiwiY3JlYXRlZF9hdCI6IjIwMjEtMDMtMDggMTQ6NTI6NDUuMjY2ODQ5MDAwIFVUQyJ9
```

**Comment by abitrolly** [comment]
@leszekhanusz where do you get that `after:eyJpZCI6IjgwNDc5NDc3IiwiY3JlYXRlZF9hdCI6IjIwMjEtMDMtMDggMTQ6NTI6NDUuMjY2ODQ5MDAwIFVUQyJ9` from?

**Comment by abitrolly** [comment]
Regarding different schema support, it is ok for `cli` tool to fail with the message that pagination is not supported for the specified scheme.

**Comment by leszekhanusz** [comment]
> @leszekhanusz where do you get that `after:eyJpZCI6IjgwNDc5NDc3IiwiY3JlYXRlZF9hdCI6IjIwMjEtMDMtMDggMTQ6NTI6NDUuMjY2ODQ5MDAwIFVUQyJ9` from?

This is the endCursor value returned from one previous query with only the first variable set. This is all explained in the GitLab pagination docs.

**Comment by abitrolly** [comment]
@leszekhanusz right, but your example doesn't include the part how that returned values ended up being a parameter to `gql-cli`. What is the officially recommended way for `gql-cli` users to work with paginated data?

**Comment by leszekhanusz** [comment]
Sorry, you don't seem to understand. All this is irrelevant to gql-cli.

The purpose of gql-cli is to send a GraphQL request towards a GraphQL endpoint and to print the result in the terminal.

GrapĥQL itself has no concept of pagination at all. How you use the data after is your problem.

**Comment by abitrolly** [comment]
I understand that `gql-cli` is not the command line tool that can support pagination, and the developers are not interested to help users query the data that is only accessible through pagination interface.

Contrary to what you said, GraphQL does have pagination concept - https://graphql.org/learn/pagination/

**Comment by RolandColored** [comment]
> I understand that `gql-cli` is not the command line tool that can support pagination, and the developers are not interested to help users query the data that is only accessible through pagination interface.
> 
> Contrary to what you said, GraphQL does have pagination concept - https://graphql.org/learn/pagination/

Came here to say the same. 😄 
Actually the reason to use a library is to reduce the amount of repetitive work. Handling pagination definitely falls under this topic.

**Comment by abitrolly** [comment]
@RolandColored do you think it is worth to put a license for this code? I created a gist out of it - https://gist.github.com/abitrolly/2b5351962b3b6ed57ce7141599fcde7e - it even worked at some point, but right now needs some fixes for Jupyter notebook.

I am trying to figure out how the pagination works here. Does it fetch one repo per page? Because in my first successful run there was only one count per page, and I am not sure how many repos this count included.

**Comment by RolandColored** [comment]
> @RolandColored do you think it is worth to put a license for this code? I created a gist out of it - https://gist.github.com/abitrolly/2b5351962b3b6ed57ce7141599fcde7e - it even worked at some point, but right now needs some fixes for Jupyter notebook.

Feel free to use it like you need.


> I am trying to figure out how the pagination works here. Does it fetch one project per page? Because in my first successful run there was only one count per page, and I am not sure how many projects this count included.

Yes you are right. It actually does "extreme" pagination and fetches only one project per page. This is because of a speciality of the GitLab API: The jobs count I'm interested in will only be calculated for the first project - no matter how much projects are requested.

For all other queries you can and should a higher limit (e.g. `first: 100` which is the maximum). Then you'll have a list of lists in the end which needs to be joined together afterwards.
