### ISSUE TITLE
DSL - Datetime argument serialization failing

### ISSUE THREAD

**Issue by FelixNuvolar** [graphql-python/gql#209]
Hello,
Using GQL 2.0.0, and trying to pass datetime arguments in mutation requests, we realised that the result value of the DSL serialisation was none for such fields.

It seems related to the way Scalar types are build, passing _none as a serializer method (/lib/python3.9/site-packages/graphql/utils/build_client_schema.py:146)

Are we missing something or is this a bug ? For now the only solution we found is to monkey patch the args() method of the  DSLField class to implement custom serialization.

Best regards,
Felix

**Comment by leszekhanusz** [comment]
Sorry, custom scalars are not yet supported.
