### ISSUE TITLE
Client.execute should take optional operation_name

### ISSUE THREAD

**Issue by barbieri** [graphql-python/gql#21]
Eventually the document may contain more than one query or mutation. In this case the queries must be named and `operationName` should say which one to execute.

Not that useful in real practice, but sometimes while developing it's handy to keep feeding the same file and just change which operation to use.

**Comment by barbieri** [comment]
just saw #17 adds that, close this issue when that's landed.

**Comment by Cito** [comment]
This feature has now been added in the v2 and v3 (master) branches, so we can finally close this.
