### ISSUE TITLE
Feature request: support for custom json serialization

### ISSUE THREAD

**Issue by markedwards** [graphql-python/gql#216]
It would be useful to be able to specify a custom `json_dumps ` callable for the transport.  Right now gql is hardcoded to use `json.dumps` from the standard library, and that has performance issues as well as poor serialization.  It is common to have to provide Enum or datetime objects in variables, for instance, and without the ability to specify a custom callable its necessary to pre-process values which is inefficient and annoying to implement.

Any appetite for such a capability in the future?

**Comment by leszekhanusz** [comment]
What is going to be implemented next is custom scalars, this will work only if the schema is available locally.

You'll define a [GraphQLScalarType](https://github.com/graphql-python/graphql-core/blob/ab209c49d6e350c311829ace6786fed51382166e/src/graphql/type/definition.py#L304) to define the serialize/unserialize methods and add these custom scalars to the schema, then during the execute, the variables will be encoded using [ast_from_value](https://github.com/graphql-python/graphql-core/blob/ab209c49d6e350c311829ace6786fed51382166e/src/graphql/utilities/ast_from_value.py#L37) then serialized again.

This step should be opt-in as it will be less efficient as what we have now.

Your proposition could also be implemented in a few lines of code by having the dumps function defined as an argument with a default value for the execute/subscribe functions for all the transports. I'll accept a PR if it comes with tests.
