### ISSUE TITLE
[linux issue] - ImportError: cannot import name 'HeadersLike' from 'websockets.http'

### ISSUE THREAD

**Issue by vranky** [graphql-python/gql#219]
I have code snippet for asynchronous gql subscription through websocket client which works correctly on my darwin but when I have troubles when i run code below on some linux machines.

ws_client implementation:
```
async def ws_client(env, user_name, password):

    transport = WebsocketsTransport(url=f"wss://myservice/api/graphql",
                                    init_payload={
                                        "authorization": f"bearer {token}",
                                        "sessionId": uuidr,
                                        "x-tenant": xyz,
                                    })

    client = Client(transport=transport, fetch_schema_from_transport=True)

    async with client as session:
        task1 = asyncio.create_task(execute_subscription(session))

        await asyncio.gather(task1)
  
 asyncio.run(ws_client("env", "usrName", "Password"))

```

Python version:
3.8, 3.9

websocket-client version:
1.1.0

Current state after ws client start on linux machines:

```
Traceback (most recent call last):
  File "graphql/ws_client_async.py", line 10, in <module>
    from gql.transport.websockets import WebsocketsTransport
  File "/var/lib/jenkins/jobs/lts-perf-tests/workspace/python_3_8/lib/python3.8/site-packages/gql/transport/websockets.py", line 11, in <module>
    from websockets.http import HeadersLike
ImportError: cannot import name 'HeadersLike' from 'websockets.http' (/var/lib/jenkins/jobs/lts-perf-tests/workspace/python_3_8/lib/python3.8/site-packages/websockets/http.py)
```

Pls provide some feedback how can i deal with exception **ImportError: cannot import name 'HeadersLike' from 'websockets.http'.**

**Comment by leszekhanusz** [comment]
You need to the correct version of `websockets`.

For `gql 3.0.0a6`, you need **websockets>=9,<10**
For `gql 3.0.0.a5` and before you need **websockets>=8.1,<9**

If you install gql using [the installation instructions using pip](https://gql.readthedocs.io/en/v3.0.0a6/intro.html#installation), then the correct dependencies should be installed automatically.

**Comment by vranky** [comment]
Many thanks, that was root cause!
