### ISSUE TITLE
Allow errors and data

### ISSUE THREAD

**Issue by barbieri** [graphql-python/gql#22]
Sometimes the returned object contains both `errors` and `data`, for instance when executing a query such as:

```graphql
query {
   fieldOk
   fieldFailed
}
```

If `fieldFailed` is null-able and during its resolve it fails, the return will be something like:

```json
{"data": {"fieldOk": "value", "fieldFailed": null},
 "errors": [{"message": "some error message", "paths": ["fieldFailed"]}]
}
```

Then throwing an exception is not the best thing to do. My suggestion is to just pass-thru the result dict and let the user handle that -- but that breaks API, then you may consider a new `execute()` method.

**Comment by barbieri** [comment]
Also note that if you pass a field that doesn't exist, then `errors` is returned, but as HTTP status `400`, then it must be handled to return the proper object. Example:

```
query {
  nonExistentField
}
```

Returns `HTTP 404` and document:

```
{"errors": [{"message": "...."}]}
```

**Comment by Cito** [comment]
This should be better in gql 0.4.0 - if there are still issues, please repoen.
