### ISSUE TITLE
Validation for custom scalars

### ISSUE THREAD

**Issue by manminne** [graphql-python/gql#221]
Hey, 
just a quick question:
I saw that custom scalars are not yet supported. To still use the library for this purpose, I set _fetch_schema_from_transport_ to False expecting that this would skip the client-side schema validation.
However, unfortunately, I still receive an error message when passing a String to my custom scalar "date": gql.transport.exceptions.TransportQueryError: Invalid time value

Is there anything that I need to be aware of in terms of client-side schema validation? Any suggestions on how to resolve this?

**Comment by leszekhanusz** [comment]
This error comes from the backend, it has nothing to do with schema validation.

The format for the date is probably incorrect.
