### ISSUE TITLE
Cannot import name 'DocumentNode' from 'graphql'

### ISSUE THREAD

**Issue by ABCALPHA** [graphql-python/gql#224]
Hi, I am having this issue "Cannot import name 'DocumentNode' from 'graphql'"
Have checked my package version as below. Seems they are compatible. Did  anyone have similar issues? Thanks

gql  (3.0.0a6)
 yarl<2.0,>=1.6 (from gql) (1.6.3)
 graphql-core<3.2,>=3.1.5 (from gql) (3.1.5)
multidict>=4.0 (from yarl<2.0,>=1.6->gql) (5.1.0)
 idna>=2.0  (from yarl<2.0,>=1.6->gql) (3.2)
typing-extensions>=3.7.4  (from yarl<2.0,>=1.6->gql) (3.10.0.0)
python 3.7

**Comment by leszekhanusz** [comment]
Strange, it seems someone had a similar problem (Issue #181) and was able to solve it by reinstalling graphql-core

**Comment by leszekhanusz** [comment]
Are you sure about your dependencies ?

What is the result of:

```python
from graphql import __version__ as version_graphql                                                                      
from gql import __version__ as version_gql                                                                                                                                           
                                                                                                                        
print (f"GraphQL version {version_graphql}")                                                                            
print (f"GQL version {version_gql}")      
```

**Comment by ABCALPHA** [comment]
Hi Hanusz, 
Thanks for following up. I have reinstalled the graphql-core. It is working fine now. The dependencies are as below just in case someone runs into similar issues. Thanks again.

gql (3.0.0a6)
yarl<2.0,>=1.6 (from gql) (1.6.3)
graphql-core<3.2,>=3.1.5 (from gql) (3.1.5)
multidict>=4.0 (from yarl<2.0,>=1.6->gql) (5.1.0)
idna>=2.0 (from yarl<2.0,>=1.6->gql) (3.2)
typing-extensions>=3.7.4 (from yarl<2.0,>=1.6->gql) (3.10.0.0)
python 3.7

**Comment by leszekhanusz** [comment]
Good!

**Comment by dieend** [comment]
Encountering the same issue

```
virtualenv venv
. ./venv/bin/activate
pip install --pre 'gql[all]'
python graphql.py
```
error
```
Traceback (most recent call last):
  File "graphql.py", line 4, in <module>
    from graphql import __version__ as version_graphql
  File "/Users/adinata/workspace/credit_card/release-eng/scripts/buildkite/graphql.py", line 4, in <module>
    from graphql import __version__ as version_graphql
ImportError: cannot import name '__version__' from 'graphql' (/Users/adinata/workspace/credit_card/release-eng/scripts/buildkite/graphql.py)
```

Running `pip freeze`
```
> pip freeze
aiohttp==3.7.4.post0
async-timeout==3.0.1
attrs==21.2.0
certifi==2021.5.30
chardet==4.0.0
charset-normalizer==2.0.4
gql==3.0.0a6
graphql-core==3.1.6
idna==3.2
multidict==5.1.0
requests==2.26.0
typing-extensions==3.10.0.2
urllib3==1.26.6
websockets==9.1
yarl==1.6.3
```

Python version
```
> python --version
Python 3.7.3
```

**Comment by leszekhanusz** [comment]
@dieend 
 I think you should rename your script to something else than `graphql.py`

**Comment by Cito** [comment]
The reason is explained [here](https://docs.python.org/3/tutorial/modules.html#the-module-search-path).

**Comment by dieend** [comment]
🤦 it's been a while since writing python. Of course. Thank you @leszekhanusz
