### ISSUE TITLE
Error resolving dependencies through Poetry on 3.0.0

### ISSUE THREAD

**Issue by Vichoko** [graphql-python/gql#229]
# Description

In [setup.py](https://github.com/graphql-python/gql/blob/master/setup.py), the following 3 requirements are exposed in some non-standard named variables:
```
install_aiohttp_requires = [
    "aiohttp>=3.7.1,<3.8.0",
]

install_requests_requires = [
    "requests>=2.23,<3",
]

install_websockets_requires = [
    "websockets>=9,<10",
] 
```

This is breaking package manager dependency resolvers as they don't stick to [PEP8 `setup.py` `setup_requires` naming conventions](https://www.python.org/dev/peps/pep-0518/).

As it is, the newest 3.0.0 pre-releases are not installable through Poetry and maybe other package managers, because of these non-standard requirement lists.

## Replicate

While bumping GQL from 3.0.0a2 to 3.0.0a6 with Poetry we get the following result:
```
$ poetry update
Updating dependencies
Resolving dependencies... (12.5s)

Writing lock file

Package operations: 0 installs, 2 updates, 8 removals

  • Removing aiohttp (3.6.2)
  • Removing async-timeout (3.0.1)
  • Removing certifi (2021.5.30)
  • Removing chardet (3.0.4)
  • Removing charset-normalizer (2.0.4)
  • Removing requests (2.26.0)
  • Removing urllib3 (1.26.6)
  • Removing websockets (8.1)
  • Updating multidict (4.7.6 -> 5.1.0)
  • Updating gql (3.0.0a2 -> 3.0.0a6)
```

This uninstalls the exposed requirements, and it's dependencies.
Then, the whole code crashes with import errors:
```
Traceback (most recent call last):
  File "/Users/vicenteoyanedel/opt/miniconda3/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/vicenteoyanedel/opt/miniconda3/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/vicenteoyanedel/git/data-store-client/tests/test_client.py", line 8, in <module>
    from data_store_client import DataStoreClient
  File "/Users/vicenteoyanedel/git/data-store-client/data_store_client/__init__.py", line 2, in <module>
    from data_store_client.client import DataStoreClient
  File "/Users/vicenteoyanedel/git/data-store-client/data_store_client/client.py", line 6, in <module>
    from gql.transport.requests import RequestsHTTPTransport
  File "/Users/vicenteoyanedel/git/data-store-client/.venv/lib/python3.8/site-packages/gql/transport/requests.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

## Proposed solution

Stick to PEP8 specification and include all requirements in [`setup_requires` list.](https://www.python.org/dev/peps/pep-0518/#rationale)

**Comment by leszekhanusz** [comment]
Since [3.0.0a4](https://github.com/graphql-python/gql/releases/tag/v3.0.0a4), gql added optional dependencies.

This allows users to install gql with only the necessary dependencies for them (See [the documentation](https://gql.readthedocs.io/en/latest/intro.html#installation))

Using poetry, it is possible to specify extra dependencies in your pyproject.toml file. Something like this:
```python
[tool.poetry.dependencies]
gql = {version = "3.0.0a6", extras = ["requests"]}
```

**Comment by mirkan1** [comment]
this is unnecessarily complicated.

**Comment by theodale** [comment]
Agreed, maybe make it opt out?
