### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by metakermit** [graphql-python/gql#23]
Just checking to ask if this project is still maintained? I see that Graphene itself allows one to query a GraphQL API, so I'm wondering if that's recommended as a client instead? Also, is there any documentation anywhere? (nothing is linked from the README)

**Comment by ivcandela** [comment]
+1

**Comment by luvwinnie** [comment]
+1

**Comment by Speedy1991** [comment]
>  I see that Graphene itself allows one to query a GraphQL API, so I'm wondering if that's recommended as a client instead?

Sure, Server to Server communication for instance

**Comment by rhymes** [comment]
@Speedy1991 how? It's not clear to me how to query a server using graphene.

Thanks

**Comment by stegben** [comment]
I fork this project for temporary usage:
`https://github.com/Yoctol/gql-fork`

You may `pip install gql-fork` without modifying any code.

**Comment by rhymes** [comment]
@stegben have a look also at https://github.com/itolosa/pygql/ - it is maintained

**Comment by ariebovenberg** [comment]
I'm working on an alternative GraphQL client, if anyone is interested: [link](https://github.com/ariebovenberg/quiz)

**Comment by Cito** [comment]
Closing this - please follow up in #50
