### ISSUE TITLE
Feature request: Websocket transport to support verify_ssl=False

### ISSUE THREAD

**Issue by alexisrolland** [graphql-python/gql#233]
Hello and thank you very much for maintaining this package!

I have been looking into possible usage of subscriptions and it looks very promising. I checked the doc:

- Here: https://gql.readthedocs.io/en/v3.0.0a6/usage/subscriptions.html
- And here: https://gql.readthedocs.io/en/v3.0.0a6/transports/websockets.html

I noticed the Websockets SSL transport requires to setup a certificate verification. This is very troublesome in some situations where developers would not have access to the machine on which the script will run (ex: distribution of SDKs...). I was wondering if you would consider implementing a feature like `verify_ssl=False` similar to what exists in the `requests` package so that we could skip the certificate setup.

Thanks again for you hard work on this wonderful package!

**Comment by leszekhanusz** [comment]
**Obviously this is a very bad idea.**

Under the hood, gql uses the [websockets](https://websockets.readthedocs.io/en/stable/intro.html) dependency.

Apparently [it is possible to disable certificate verification of websockets](https://websockets.readthedocs.io/en/stable/faq.html#how-do-i-disable-tls-ssl-certificate-verification) by playing with the `ssl` argument of the `connect` method of websockets.

So you could try something like this:

```python
ssl_context = ssl.create_default_context()                                                                          
ssl_context.check_hostname = False                                                                                  
ssl_context.verify_mode = ssl.CERT_NONE

transport = WebsocketsTransport(url='wss://your_server/graphql', ssl=ssl_context)
```

**Comment by alexisrolland** [comment]
Thank you for your quick answer! Your solution to this very bad idea works :)
It allows me to experiment with subscriptions.

On a different topic, I'm wondering if I haven't discovered a bug in the process. The code I'm running returns the following error message:

> gql.transport.exceptions.TransportQueryError: {'message': 'Only subscriptions are allowed over websocket transport'}

But what I run is an actuall subscription from what I can tell. I reused the example from https://gql.readthedocs.io/en/v3.0.0a6/transports/websockets.html#websockets-transport

```
import asyncio
import logging
import ssl

from gql import Client, gql
from gql.transport.websockets import WebsocketsTransport
logging.basicConfig(level=logging.INFO)

async def main():
    token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
    headers = {"Authorization": token}

    ssl_context = ssl.create_default_context()
    ssl_context.check_hostname = False
    ssl_context.verify_mode = ssl.CERT_NONE

    transport = WebsocketsTransport(url='wss://xxx.org/graphql', headers=headers, ssl=ssl_context)

    # Using `async with` on the client will start a connection on the transport
    # and provide a `session` variable to execute queries on this connection
    async with Client(transport=transport, fetch_schema_from_transport=True) as session:
        # Request subscription
        subscription = gql("""
            subscription job {
                jobsSubscription {
                    job {
                        id
                        status
                    }
                }
            }
        """)
        async for result in session.subscribe(subscription):
            print(result)

asyncio.run(main())
```

**Comment by leszekhanusz** [comment]
When you use `fetch_schema_from_transport=True`, the first request made to the backend is actually an introspection query (See [schema validation](https://gql.readthedocs.io/en/v3.0.0a6/usage/validation.html))

You can see the messages exchanged between the client and the server by [activating debug logs](https://gql.readthedocs.io/en/v3.0.0a6/advanced/logging.html).

In your case, it appears that the backend only allows subscriptions over the websockets transport so to disable the introspection query, you can try with `fetch_schema_from_transport=False`

**Comment by alexisrolland** [comment]
Aaaaand it's working like a charm! Thank you for your support on this <3
Keep up the great work!
