### ISSUE TITLE
Question: How to work around the error "Transport is already connected"

### ISSUE THREAD

**Issue by alexisrolland** [graphql-python/gql#238]
I have built a Python SDK for my application which exposes a simple subscription method. The method takes as input a Job Id and a callback function. The idea is that when the subscription receives an update of the job, the callback function is called. Here is the method (note it is running in a separate thread to not block the main thread/application)

```python
def subscribe_job(self, job_id: int, callback: Callable) -> dict:
    """Subscribe to a job, receive the job information every time it is updated and pass it to a callback function."""

    async def _exec_subscription(subscribe_job: str, variable_values: dict, callback: Callable):
        """Execute subscription and callback function."""

        async with self._ws_client as session:
            async for response in session.subscribe(gql(subscribe_job), variable_values=variable_values):
                callback(response['jobSubscriptionById']['job'])

    def _run_subscription_loop(loop, subscribe_job: str, variable_values: dict, callback: Callable):
        """Create asyncio loop and run it."""

        loop.run_until_complete(_exec_subscription(subscribe_job, variable_values, callback))

    # Build GraphQL mutation to delete job
    subscribe_job = """
        subscription jobSubscription($jobId: Int!) {
            jobSubscriptionById(id: $jobId) {
                job {
                    id
                    spaceId
                    applicationId
                    configurationId
                    title
                    description
                    status
                    step
                    progress
                }
            }
        }
    """

    # Build variables dictionary
    variable_values = {
        'jobId': job_id
    }

    # Get running asyncio loop or create new one if it does not exist
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
    
    # Start new thread
    thread = threading.Thread(target=_run_subscription_loop, args=(loop, subscribe_job, variable_values, callback))
    thread.start()
```

This works well when I call `subscribe_job` one time. But if I call it a second time for a different job, I get the error message:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/craft/craft.py", line 1920, in _run_subscription_loop
    loop.run_until_complete(_exec_subscription(subscribe_job, variable_values, callback))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/tmp/craft/craft.py", line 1913, in _exec_subscription
    async with self._ws_client as session:
  File "/usr/local/lib/python3.7/site-packages/gql/client.py", line 243, in __aenter__
    await self.transport.connect()
  File "/usr/local/lib/python3.7/site-packages/gql/transport/websockets.py", line 608, in connect
    raise TransportAlreadyConnected("Transport is already connected")
gql.transport.exceptions.TransportAlreadyConnected: Transport is already connected
```

I think this is probably a problem with my design rather than gql itself but I was wonering if you would you have any idea how to work around this situation?

Thank you
Alexis

**Comment by alexisrolland** [comment]
Okay after doing some further research, I understand that each client subscription needs it's own websocket connection. So I simply create a new websocket client in my function `_exec_subscription` instead of trying to mutualize my previous client `_ws_client` defined at class level...

**Comment by leszekhanusz** [comment]
FYI, it is possible to use the same websocket connection for multiple subscription.

Check [async advance usage](https://gql.readthedocs.io/en/v3.0.0a6/advanced/async_advanced_usage.html) in the docs.

If you want to save your session in a single class, it gets a little bit tricky (you can check issue #179 for some examples).

Also a little bit of advice, don't mix threads and asyncio if you don't need to.

**Comment by alexisrolland** [comment]
Thank you for the link and the fast answer! This example looks pretty interesting and I will try it. I know my following question is off-topic but is it possible to unblock the main thread of my program (which is mostly synchronous) using asyncio only without threading?

**Comment by leszekhanusz** [comment]
No, it is not possible.
It should be fine to use a separate thread but if you are starting from scratch I would consider to make the rest of the program async.

**Comment by alexisrolland** [comment]
Unfortunately I cannot, this is supposed to run as an add-on in Blender (https://www.blender.org/). I will try to reuse your example and adjust it to run in a different thread. Thanks!
