### ISSUE TITLE
execute function does not accept extra_args

### ISSUE THREAD

**Issue by drijhwani** [graphql-python/gql#245]
I am getting an error for execute function.

TypeError: execute() got an unexpected keyword argument 'extra_args' 

My execute function is not recognizing extra_args attribute. My gql version is 3.0.0a6 and graphql-core version is 3.1.5 Python version is 3.8.

**Comment by leszekhanusz** [comment]
Which transport are you using?
Could you please post the complete stack trace?

**Comment by drijhwani** [comment]
I am using RequestsHTTPTransport and below is the stack trace. 

ERROR    root:conftest.py:872 tests/graphqlgateway/apq_tests.py::TestGraphQlGatewayAPQ::test_apq[tc001 - Verify APQ] Failed with the following exception 
                              TypeError: execute() got an unexpected keyword argument 'extra_args'
ERROR    root:conftest.py:874 Test 'tests/graphqlgateway/apq_tests.py::TestGraphQlGatewayAPQ::test_apq[tc001 - Verify APQ]' FAILED
INFO     root:conftest.py:879 Test 'tests/graphqlgateway/apq_tests.py::TestGraphQlGatewayAPQ::test_apq[tc001 - Verify APQ]' COMPLETED
INFO     root:conftest.py:882 Test 'tests/graphqlgateway/apq_tests.py::TestGraphQlGatewayAPQ::test_apq[tc001 - Verify APQ]' DURATION=5.96612548828125
========================================================================================================================= short test summary info ==========================================================================================================================
FAILED tests/graphqlgateway/apq_tests.py::TestGraphQlGatewayAPQ::test_apq[tc001 - Verify APQ] - TypeError: execute() got an unexpected keyword argument 'extra_args'

**Comment by leszekhanusz** [comment]
`extra_args` is only for the AIOHTTPTransport. What are you trying to accomplish with it?

**Comment by drijhwani** [comment]
Thank you for the information. I am trying to test APQ (Automated Persisted Query) and my request needs to send a parameter 'extensions' as listed in this example. https://www.apollographql.com/docs/apollo-server/performance/apq/#command-line-testing

**Comment by leszekhanusz** [comment]
`extra_args` is there to be able to add arguments to the `request` method.

What you actually need is to add a new element to the `payload` dict.

We could add a new argument "extra_payload" which would allow you to add key to the payload easily.

For now, it should still be possible to do it by doing something like this:

```
extra_args={
    "json": {
        "query": print_ast(document),
        "extensions": .......
    }
}
```

About your error, if I understand correctly the TypeError is being returned from your own code? Do you have an execute method? Could you share your code?
