### ISSUE TITLE
websocket actioncable-v1-json not supported

### ISSUE THREAD

**Issue by R0hm** [graphql-python/gql#254]
Being quite new to such things as GraphQL and Websockets, it tooks to me a while to understand why my websocket connection was not working : the `WebsocketsTransport` class does not seem to support the _actioncable-v1-json_ protocol. It may be a known fact and not really an issue though ?

This websocket I'm trying to connect to can be seen in action [here](https://sorare.com/transfer_market). The associated GraphQL API has a well documented playground [here](https://api.sorare.com/graphql/playground).

Snippet of code to demonstrate the problem:
```
from gql import Client, gql
from gql.transport.websockets import WebsocketsTransport

logging.basicConfig(level=logging.DEBUG)


async def main():
    transport = WebsocketsTransport(url="wss://ws.sorare.com/cable", headers={'Origin': 'https://sorare.com'})

    # Using `async with` on the client will start a connection on the transport
    # and provide a `session` variable to execute queries on this connection
    async with Client(transport=transport) as session:
        # Subscribe to a channel
        pass
        # Send a GraphQL subscription
        pass


asyncio.run(main())
```

My understanding, based on [this interesting blog post](https://thoughtbot.com/blog/talking-to-actioncable-without-rails) is that with this protocol, once the connection is open, the server send a `{"type":"welcome"}` message buth then rather wait for the client to send a subscription message to a specified channel instead of an exchange of handshake.

I'm fairly new to this library and to websockets, but with some guidance and if this does not seem to be too complicated to implement this new protocol, maybe I could give it a try when I'll have some time ? But I'll need some hints 😅

**Comment by leszekhanusz** [comment]
gql supports different websockets protocols with different transports.

- [Apollo](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md) and [Graphql-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) protocols with the WebsocketsTransport.
- Phoenix channel protocol with the PhoenixChannelWebsocketsTransport
- Soon, [AWS appsync websocket protocol with the AppSyncWebsocketsTransport](https://github.com/graphql-python/gql/pull/239)

The actioncable protocol is not supported for now.
If you want to support the actioncable protocol, you could create another transport. It can be merged to gql if it comes with tests with 100% code coverage and documentation.
If you want to contribute to gql, please read the [CONTRIBUTING.md](https://github.com/graphql-python/gql/blob/master/CONTRIBUTING.md) file

**Comment by leszekhanusz** [comment]
Is this protocol actually used in other websites or is it specific to this one site?

If it is a custom protocol I'm afraid it won't be added here and we could close this issue.

**Comment by R0hm** [comment]
Hard to say as I have not a lot of experience on this kind of stuff. I would bet it is though, as the documentation I found above was not written by the company hosting the API I was trying to fetch data from.

**Comment by leszekhanusz** [comment]
I implemented the transport in a separate package.
See [gqlactioncable](https://github.com/leszekhanusz/gql-actioncable) for more info and don't hesitate to give your feedback.
