### ISSUE TITLE
Float not recognized as Variable

### ISSUE THREAD

**Issue by Taft72** [graphql-python/gql#260]
Hi,

this is my first Github issue, so please bear with me. I'm trying to query a data base in a loop while using a filter on a specific threshold. I created a minimal example:

```
# -*- coding: utf-8 -*-
from gql import gql, Client
from gql.transport.requests import RequestsHTTPTransport

# set up Transport and Client
sample_transport=RequestsHTTPTransport(
    url = 'https://[x]',
    verify=True,
    retries=3,
)
client = Client(transport=sample_transport)

# hardcoded query command
query_command = """query
    test($threshold: Float!) {
      pairs(first: 10, where: { reserveUSD_lt: $threshold }) {
        reserveUSD
      }
    }"""
query = gql(query_command)

# get response
params = { "threshold": 10000 }
response = client.execute(query, variable_values=params)
print(response)
```

When running this code, I get the following error:

```
Traceback (most recent call last):
  File "[x]\testquery.py", line 25, in <module>
    response = client.execute(query, variable_values=params)
  File "[x]\Miniconda3\envs\[x]\lib\site-packages\gql\client.py", line 78, in execute
    raise Exception(str(result.errors[0]))
Exception: {'locations': [{'line': 1, 'column': 12}], 'message': 'Variable `threshold` must have an input type'}
```

Float is not being recognised as input type and I do not understand why. With Int it works, String and ID also get recognized.

Unfortunately I can't use Int as a workaround in this case, because I need to filter by very large values (bigger than a billion), which gql seems to automatically convert into a Float, even when passed as int.

The packge I'm using is the latest version, installed via Anaconda. Version: 2.0.0, Build: pyh9f0ad1d_0, Channel: conda-forge

If you need any more information, please let me know.

**Comment by leszekhanusz** [comment]
Could you try it with a more recent gql version ? `3.0.0b1` for example. Please check the [installation instructions](https://gql.readthedocs.io/en/v3.0.0b1/intro.html).

**Comment by leszekhanusz** [comment]
Also you don't get to choose the type of the variable, it is the backend which decides what is the type of each input variable.

Do you have the Schema?
What is the type of `reserveUSD_lt` in the Schema?

**Comment by Taft72** [comment]
> What is the type of reserveUSD_lt in the Schema?
I assumed reserveUSD is a float value, but I just checked and the return value is actually String. I'm sorry I didn't check this earlier.

Is there any way to sort the results numerically when the return value is String and there are are no leading zeroes? My last resort would be to dynamically format the query-string during runtime, I wanted to avoid that.

**Comment by leszekhanusz** [comment]
If I understand correctly, with Uniswap `reserveUSD_lt` is actually a custom scalar named `BigDecimal` which serialize to a `String`
In that case, if you use a recent version of gql, then you could create your own custom scalar to serialize and parse to whichever python object you want.
See the [custom scalars help](https://gql.readthedocs.io/en/v3.0.0b1/usage/custom_scalars_and_enums.html)

**Comment by leszekhanusz** [comment]
Also: [you should never use floats or double to represent money](https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency)

**Comment by Taft72** [comment]
> If I understand correctly, with Uniswap ```reserveUSD_lt``` is actually a custom scalar named ```BigDecimal```

That's the Input Type I've been missing for days. Thank you for your help!
