### ISSUE TITLE
cookies not available in v.0.1.0

### ISSUE THREAD

**Issue by phillipwei** [graphql-python/gql#27]
Not sure how the project is being built, but when I tried to call `RequestsHTTPTransport` with `cookies` it failed. Though the code says this is being passed through to `HTTPTransport` that expects it, an `inspect.getargspec(HTTPTransport.__init__)` shows that `cookies` is not defined, so this does not work.

**Comment by ZoeyeoZ** [comment]
Please see https://github.com/graphql-python/gql/issues/36

**Comment by Cito** [comment]
Should be available now in v0.2.0 and v.0.3.0.
