### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by hexdecimal16** [graphql-python/gql#270]
I am getting this error when trient to make a mutation on my graphql server running on aws ec2 instance. The server is working properly as the apollo-client on my front end application is able to query the server.

`qgl.transport.exceptions.TransportQueryError: {
'message': 'Connection "default" was not found.', '
locations': [{'line': 2, 'column': 3}],
'path': ['checkAndUpdateStock'],
'extensions': {'code': 'INTERNAL_SERVER_ERROR'}
}`

**Comment by leszekhanusz** [comment]
A `TransportQueryError` means that the error is coming from the backend.
You can check the messages exchanged between the client and the backend by [activating debug logs](https://gql.readthedocs.io/en/v3.0.0b1/advanced/logging.html)

**Comment by dipika-arable** [comment]
I am facing below issue in backend 
ClientAbortException
java.io.IOException: Broken pipe

And below on client.

gql.transport.exceptions.TransportServerError: 503 Server Error: Service Temporarily Unavailable for url

**Comment by leszekhanusz** [comment]
@dipika-arable Please don't add unrelated comments to previously closed issues.

Your problem looks like a backend problem. Please open another issue by following the template and providing code and debug logs if you thing gql is at fault.
