### ISSUE TITLE
Using `gql` for query editing

### ISSUE THREAD

**Issue by abitrolly** [graphql-python/gql#272]
Can `qgl` be used to programmatically modify queries?

For example to transform this request.
```
    query getContinents {
      continents {
        code
        name
      }
    }
```
To this one.
```
    query getContinents {
      continents (code:"AF") {
        code
        name
      }
    }
```
`gql.gql()` parses the input into `graphql` AST `DocumentNode`, but it is not clear which methods are available to modify it, and how to write the query back as a string.

**Comment by leszekhanusz** [comment]
You can use the [DSL module](https://gql.readthedocs.io/en/v3.0.0b1/advanced/dsl_module.html) to create requests programmatically.

To convert a `DocumentNode` to string again, you can use the `print_ast` method of graphql.

**Comment by abitrolly** [comment]
I was able to convert a query to `DocumentNode` and back to string.
```python
import gql

dg = gql.gql("""
    query getContinents {
      continents {
        code
        name
      }
    }
""")

from graphql import print_ast
print(print_ast(dg))
````
```
query getContinents {
  continents {
    code
    name
  }
}
```

However, I don't see any methods that allow to traverse the tree to find `continents` node and add a parameter to it.

**Comment by abitrolly** [comment]
It is not enough for editing to just use DSL to create queries. This one is addressed.

* [x] How to parse `query` into "edit mode" and get back the string

However, two more questions are still left.

* [ ] How to find AST node that needs modification?
* [ ] How to modify it?

**Comment by leszekhanusz** [comment]
This not really a gql question but instead a [graphql-core](https://github.com/graphql-python/graphql-core) question.

You might want to look at the dsl module source code which does exactly that.
For example: [to add an argument](https://github.com/graphql-python/gql/blob/4554e4b4927b9a772329bdcd627a1b8065e74d50/gql/dsl.py#L787)
