### ISSUE TITLE
gql execution issue on hasura

### ISSUE THREAD

**Issue by BAnilKumar** [graphql-python/gql#284]
Hi Team,
I am trying to connect to hasura with gql package, with below code

```
from gql import gql, Client
from gql.transport.aiohttp import AIOHTTPTransport

# Select your transport with a defined url endpoint
transport = AIOHTTPTransport(url="https://XXX.hasura.app/v1/graphql")

# Create a GraphQL client using the defined transport
client = Client(transport=transport, fetch_schema_from_transport=True)

# Provide a GraphQL query
query = gql(
    """
    query getOrders {
      orders {
        id
        user_id
      }
    }
"""
)

# Execute the query on the transport
result = client.execute(query)
print(result)

```
Resuted:
AssertionError: Cannot run client.execute(query) if an asyncio loop is running. Use 'await client.execute_async(query)' instead.

2. used client.execute(query) but it did not get chance to execute (waited for 10 min)
3. as per the documentation used asyncio.get_running_loop() returned <Task pending name='Task-4' coro=<main() running at <ipython-input-19-6ed896146c3a>:1>>

1. above results from spyder
2. in Pycharm "TypeError: Type query_root must define one or more fields."
3. in CLI got cyclic error related to Client module

can you suggest me?

Thanks,
Anil

**Comment by leszekhanusz** [comment]
You have to use [the async method](https://gql.readthedocs.io/en/latest/async/async_usage.html#ipython) if you want to use gql with Spyder.

If that does not help, please tell me which version of gql do you use and provide a full stack trace for any error you encounter.

**Comment by leszekhanusz** [comment]
Here is an executable example which works with Spyder (I just tested it):

```python
import asyncio

from gql import Client, gql
from gql.transport.aiohttp import AIOHTTPTransport


async def main():

    transport = AIOHTTPTransport(url="https://countries.trevorblades.com/graphql")

    # Using `async with` on the client will start a connection on the transport
    # and provide a `session` variable to execute queries on this connection
    async with Client(
        transport=transport, fetch_schema_from_transport=True,
    ) as session:

        # Execute single query
        query = gql(
            """
            query getContinents {
              continents {
                code
                name
              }
            }
        """
        )

        result = await session.execute(query)
        print(result)


loop = asyncio.get_running_loop()
loop.create_task(main())
```

**Comment by leszekhanusz** [comment]
Please reopen this issue if you have more info.
