### ISSUE TITLE
Code generation for typed operations?

### ISSUE THREAD

**Issue by jhnnsrs** [graphql-python/gql#289]
Not sure if it is planned for the client or outside of its scope, but I have developed a little code generation
tool that extracts operations,fragments, scalars and generated a pydantic compatible schema for the client
side (a la graphql-codegen). Its at an early stage but I was wondering if there is interest in such a feature for "gql
project" (gql-codegen).

https://github.com/jhnnsrs/turms

Thanks for the great work!

**Comment by leszekhanusz** [comment]
There was a previous attempt with dataclasses in PR #185 but it was a bit too soon before custom scalars were implemented in  gql so it is now not in sync with the current code.

**Comment by jhnnsrs** [comment]
Ah I knew I couldn't have been the only one ;) I thought about dataclasses but opted for pydantic because of the ecosystem especially surrounding custom fields. It should be not hard thought to convert the actual logic to use dataclasses as I am just generating python ast and then call ast.unparse on the generated tree. Would there be an interest in a PR at a later stage?

**Comment by geekscrapy** [comment]
So I'm on the same page, would this allow you to point gql-cli at a gql server and it generates a Python classes to interact with that schema?
If so, I'd love this as it would help a lot with graphql client dev to allow IDEs to assist in the development process.

**Comment by jhnnsrs** [comment]
That's pretty much the idea yes. You would write client side operations (.graphql) and use these to generate annotated classes. turms has matured a little bit more, if you want to give it a try, would love to know if it fits your needs.

**Comment by leszekhanusz** [comment]
After much hesitation it has been decided to leave code generation code outside of this repo.
Code generation tools should be provided by a separate package to keep gql manageable and allow different code generation approaches to be made concurrently.
gql will concentrate on being the client with multiple transport that it is now.
I hope you understand.

**Comment by jhnnsrs** [comment]
Surely completely understood. Better to separate concerns.  I will set up an example on turms how to set it up with gql!

**Comment by jhnnsrs** [comment]
https://github.com/jhnnsrs/turms/tree/master/examples/gql-usage

Freshly merged ;) I hope that helps? If you have any problems, i would love some feedback!

**Comment by huyz** [comment]
@jhnnsrs Thanks! I'll try to give feedback.
