### ISSUE TITLE
Any example code?

### ISSUE THREAD

**Issue by vivek14632** [graphql-python/gql#29]

**Comment by ahussain3** [comment]
Would be great to see what format the GQL schema is expected in

**Comment by timotheecour** [comment]
+1 on this; I'm only seeing how to parse the client, but not the schema
```
query = gql('''
{
  hello
}
''')
```

**Comment by ahussain3** [comment]
I added some extra examples here: https://github.com/graphql-python/gql/pull/32

**Comment by ephes** [comment]
On the server side I use graphene-django and graphiql and it's easy to from apollo-client in javascript, but today I tried to send some queries in a jupyter notebook and stumbled upon this python client. Had to look in the source to find out how to specify the schema. Would be great if the readme example could be a little bit more elaborate.

```python
from gql import gql, Client
from gql.transport.requests import RequestsHTTPTransport

transport = RequestsHTTPTransport("http://localhost:8000/graphql/")
client = Client(transport=transport)
```
