### ISSUE TITLE
Incompatible dependency versions with graphene-sqlalchemy

### ISSUE THREAD

**Issue by faridk** [graphql-python/gql#291]
`gql` and `graphene-sqlalchemy` seem to have a dependency conflict because of the following pip errors:

```
graphene==3.0
graphene-sqlalchemy==3.0.0b1
gql==3.0.0
```
<img width="858" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/8215470/152063881-da87e57d-8160-496e-8ffb-62683f3475c7.png">

```
graphene==3.0
graphene-sqlalchemy==3.0.0b1
gql==2.0.0
```
<img width="858" alt="Pasted Graphic 5" src="https://user-images.githubusercontent.com/8215470/152063902-5b9832dd-0f2b-46fc-a955-3199cf99a40b.png">

These versions install without conflicts
```
graphene==2.1.9
graphene-sqlalchemy==2.3.0
gql==2.0.0
```
but I get this error `ImportError: cannot import name 'DSLMutation' from 'gql.dsl'` when trying to use features described [here](https://gql.readthedocs.io/en/latest/advanced/dsl_module.html)

**System info:**
 - OS: macOS 12.1
 - Python version: Python 3.9.9 (pip-22.0.2)
 - gql version: 2.0.0/3.0.0
 - graphql-core version: 2.3.2

**Comment by leszekhanusz** [comment]
Until graphene supports a more recent version of graphql-core (>=3.2), you can use the preliminary previous version of gql which supports graphql-core 3.1.*: 
`gql==v3.0.0rc0`

Not much has changed since (See [release notes](https://github.com/graphql-python/gql/releases))
