### ISSUE TITLE
64 bit integers

### ISSUE THREAD

**Issue by Coolaswa** [graphql-python/gql#295]
I am interfacing with the graphQL API of monday.com. Their item IDs have recently passed 2^31 and when I request such an item gql trows an error:
```
Int cannot represent non 32-bit signed integer value: 2300634791

GraphQL request:2:18
1 | {
2 |     boards (ids: 2300634791) {
  |                  ^
3 |     items(limit:1000){
```
monday.com have a handy API tester where I can input my query directly, and the response comes back without issue, thus leading me to believe the issue is with gql. Now, I know of this issue in the graphQL spec: https://github.com/graphql/graphql-spec/issues/73, but I am not sure it is relevant here.

**To Reproduce**
To interface with monday.com you need API authorization so I'm not sure I can provide this. But I assume trying to query a graphQL Int larger than 2^31 will reproduce this error. 

**Expected behavior**
Since the monday.com API playground gives normal results I would expect the same result from gql. 

**System info:**
 - OS: Windows 10
 - Python version: 3.9.9
 - gql version: 3.0.0
 - graphql-core version: 3.2.0

Thanks in advance for any help

**Comment by leszekhanusz** [comment]
Could you please [download the schema](https://gql.readthedocs.io/en/stable/usage/validation.html#using-a-provided-schema) with your credentials to show the type of `ids`?

Does it work correctly if you don't have a local schema (set `fetch_schema_from_transport` to `False`) ?

**Comment by Coolaswa** [comment]
Hi, thanks for your response. 
I have implemented your proposal and it seems to fix the issue I was having. Many thanks!
