### ISSUE TITLE
module 'gql.transport' has no attribute 'requests'

### ISSUE THREAD

**Issue by mohnish7** [graphql-python/gql#298]
Hello,

I am unable to get my gql query to run properly. It was running fine but all of a sudden it stopped working for me. 

```
        _transport = gql.transport.requests.RequestsHTTPTransport( url='url.com', use_json=True, )
        _transport.headers = { "User-Agent": "Mozilla/5.0 (X11; buntu; " + "Linux x86_64; rv:58.0) Gecko/0100101 Firefox/58.0", "Authorization": "Bearer {}".format(api_key), "content-type": "application/json", }
```

**System info (please complete the following information):**
 - OS: Monterey 12.0.1
 - Python version: 3.8.12
 - gql version: 3.0.0
 - graphql-core version: 3.1.7

**Comment by leszekhanusz** [comment]
It is not possible to have gql version 3.0.0 with graphql-core version 3.1.7 if you installed gql correctly.

See the [installation instructions](https://gql.readthedocs.io/en/stable/intro.html#installation)

To be certain of your gql versions, what is the output of:
```
import gql
import graphql

print ("gql: " + gql.__version__)
print ("graphql-core: " + graphql.__version__)
```
