### ISSUE TITLE
module 'gql.dsl' has no attribute 'DSLQuery'

### ISSUE THREAD

**Issue by alexmaguilar25** [graphql-python/gql#303]
**Describe the bug**
Getting an issue trying to use the DSLQuery class but getting `module 'gql.dsl' has no attribute 'DSLQuery'`. Followed the documentation on https://gql.readthedocs.io/en/latest/advanced/dsl_module.html but can't seem to get this part to work

**To Reproduce**
```
import gql
from gql import Client, dsl
...
dsl.DSLQuery(...)
```

Also, if I do a top level import, I get this error: `cannot import name 'DSLQuery' from 'gql.dsl`
```
from gql.dsl import DSLSchema, DSLField, DSLQuery
```
**Expected behavior**
I would expect to be able to use this module without any errors. My assumption is that I installed something incorrectly, but not sure

**System info (please complete the following information):**
 - OS: mac OS big sur
 - Python version: 3.9.10
 - gql version: 3.0.0
 - graphql-core version: 3.2.0

**Comment by leszekhanusz** [comment]
Sorry, I cannot reproduce your problem.

To be certain of your installed gql versions, what is the output of:
```
import gql
import graphql

print ("gql: " + gql.__version__)
print ("graphql-core: " + graphql.__version__)
```

**Comment by alexmaguilar25** [comment]
```
gql: 3.0.0
graphql-core: 3.2.0
```

Seems really odd that this is happening for me. I can try to come back and see if I find anything else..

**Comment by leszekhanusz** [comment]
You should try with a minimal example.
Does this two line script works for you:
```
from gql.dsl import DSLQuery                                                                                            
print(DSLQuery)
```

It should output `<class 'gql.dsl.DSLQuery'>`

**Comment by alexmaguilar25** [comment]
That does not work, but I've narrowed it down to being something wrong with my version in my docker container ( I should've mentioned it's running in that). I say that because doing 
```
ds = DSLSchema(None)
```
throws no error.. which it should

**Comment by leszekhanusz** [comment]
Well, of course you should run the script to detect the versions on the same environment where you have your problems...
