### ISSUE TITLE
Infinite Recursion Error

### ISSUE THREAD

**Issue by alexmaguilar25** [graphql-python/gql#304]
**Describe the bug**
So when constructing my gql client, I am able to do that successfully. When doing do, I also set `fetch_schema_from_transport=True` in there. When doing so, I try to access a query using dot notation but I get an infinite recursion error.
```
client = Client(
            transport=RequestsHTTPTransport(
                url=url,
                use_json=True,
                headers=headers
            ),
            fetch_schema_from_transport=True,
        )
with client as session:
  ds = DSLSchema(client.schema)
  product_query = ds.Query.products #this throws error `<class 'RecursionError'>-maximum recursion depth exceeded`
```

It looks like the schema is not actually getting populated into the `client` even with that variable being set to true. I checked by putting in
```
assert client.schema is not None
```
and it fails.

For what it's worth, I printed the schema using the gql-cli doing the following:
gql-cli https://server_url.com/graphql --print-schema

and, within, the schema, the Query looks like this:
```
type Query {
    ....
    products(id: ID...)
    ....
}
```
so I know that it's actually there

**Expected behavior**
I would expect this to not throw a recursion error and that I would at the very least be able to access the schema using dot notation.

**System info (please complete the following information):**
OS: mac OS big sur
Python version: 3.9.10
gql version: 3.0.0
graphql-core version: 3.2.0

**Comment by leszekhanusz** [comment]
Could you please attach your full schema ?

**Comment by leszekhanusz** [comment]
Also the schema is populated only after the establishment of the session (`with client as session:`), and it is not `None` on the line `ds = DSLSchema(client.schema)`, because otherwise it would have raise a TypeError.

**Comment by leszekhanusz** [comment]
Another option would be to [download the schema in a file and provide it to the client.](https://gql.readthedocs.io/en/stable/usage/validation.html#using-a-provided-schema)

**Comment by alexmaguilar25** [comment]
@leszekhanusz https://gql.readthedocs.io/en/latest/usage/validation.html Is the schema as a string documentation outdated? It seems like this is not possible anymore.

**Comment by leszekhanusz** [comment]
No, it is not outdated, it should work.

**Comment by alexmaguilar25** [comment]
Hm okay. If I wanted to pass in a schema to the `DSLSchema` class, since doing `Client(schema=local_schema_str).schema`returns a type of `bytes`, am I supposed to do some sort of conversion?

**Comment by leszekhanusz** [comment]
when you pass the schema to the client as a string, it is converted to a GraphQLSchema instance to produce the `schema` attribute.

**Comment by leszekhanusz** [comment]
And `DSLSchema` takes a `GraphQLSchema` as argument.

**Comment by alexmaguilar25** [comment]
Okay gotcha, I think I figured out my issue and it was due to another open issue I had where I had some version inconsistencies locally. Sorry for the inconvenience and thank you!

**Comment by leszekhanusz** [comment]
You're welcome
