### ISSUE TITLE
Invalid field for <DSLField...?

### ISSUE THREAD

**Issue by alexmaguilar25** [graphql-python/gql#305]
**Describe the bug**
So to preface, I do not think this is actually a bug - just having some trouble getting it to work.

I am getting an invalid field for a particular type in my schema. Here is an example of the following code:
```
products_query = ds.Query.data
products_query.select(ds.Data.id)  // I get error `<class 'graphql.error.graphql_error.GraphQLError'>-Invalid field for <DSLField Query::data>: <DSLField Data::id>`
```

This is how I want me query to look
```
query products($clientId: ID, $filter: ClientFilter) {
        data (clientId: $clientId, filter: $filter){
            edges {
                node {
                    id
                    name
                }
            }
        }
    }
```

Here is my graphql schema:
```
type Query {
  data(clientIds: [ID!],  filter: ClientFilter): ClientObj!
}

...

type ClientObj {
  edges: [ObjEdge!]!
  info: Info!
}

type Info {
  hasNext: Boolean
  hasBefore: Boolean
  beginCursor: string
  endCursor: string
}

type ObjEdge  {
  node: Data!
  cursor: String!
}

type Data implements Node {
  id: ID!
  name: String!
```

Is it possible to construct a query like this given the schema? Have been having some trouble with this due to my lack of knowledge with this portion of the library. My assumption on why it doesn't work is bc the field `name` on `Data` is not the top level type actually returned from the query but I'm not too sure since I thought that wouldn't matter for the sake of constructing the query only

**System info (please complete the following information):**
OS: mac OS big sur
Python version: 3.9.10
gql version: 3.0.0
graphql-core version: 3.2.0

**Comment by leszekhanusz** [comment]
You start from `ds.Query.data` and select `ds.Data.id` but `ds.Query.data` returns a `ClientObj` which only has an `edges` field, it does not have an id field.

Your query should be something like this:
```
products_query.select(
    ds.ClientObj.edges.select(
        ds.ObjEdge.node.select(
            ds.Data.id
        )
    )
)
```

**Comment by alexmaguilar25** [comment]
Okay thanks - curious though, even though my query in the DSL is wrong, isn't `id` still a valid name on the object?

**Comment by leszekhanusz** [comment]
Sorry but the last code you posted does not match the error, you probably made some mistake elsewhere.

The point is that in the DSL module, each time you use the `select` method, we will verify that you select fields which are present (directly, not further down the tree) as children of the current field in the schema.
