### ISSUE TITLE
Composing dynamic queries where fields are Python reserved keywords

### ISSUE THREAD

**Issue by chrisjclarke** [graphql-python/gql#308]
I'm trying to compose a dynamic query but one of the fields, `from` in the graphql schema is a reserved python keyword so therefore throws an error:

```
my_query = ds.Query.scores(
        filter={
            "startTimestamp": None,
            "end": None,
        },
        size=10,
        from=5,
        )

my_query.select(...)
```

Since `from` is not allowed to be passed as an argument I get the error:

```
from=5
    ^
SyntaxError: invalid syntax
```

I can't change the graphql schema, is there another way to specify this argument in a dynamic query?

Thanks

**Comment by leszekhanusz** [comment]
You could write it like this I think:

```python
my_query = ds.Query.scores(
        filter={
            "startTimestamp": None,
            "end": None,
        },
        size=10,
        **{"from":5},
)
```

**Comment by chrisjclarke** [comment]
Thanks, works perfectly!

**Comment by helderco** [comment]
The OP's example is using an argument, not a field. How do I solve for an actual field?

```python
ds.Query.container.select(
    ds.Container.from
)
```

**Comment by helderco** [comment]
I suggest we add `__getitem__` to `DSLField`:
```python
ds.Query.container.select(
    ds.Container["from"]
)
```
