### ISSUE TITLE
Update the conda package in conda-forge

### ISSUE THREAD

**Issue by motybz** [graphql-python/gql#309]
It seems that the latest conda package of gql is 2.0.0
https://anaconda.org/conda-forge/gql/files
Can you please upload the latest one? (3.1.0)
Can you please add it to the release automation?

**Comment by bollwyvl** [comment]
There is already a (failing) automated PR for this: https://github.com/conda-forge/gql-feedstock/pull/10

I'll see if i can get it cleaned up and merged.

**Comment by leszekhanusz** [comment]
All the conda stuff was made before I became maintainer. I suppose I'll need some access code or something. I'll see with the previous guys to see how we can proceed.

**Comment by motybz** [comment]
Thank you guys, please let me know if there is anything that I could help with.

**Comment by leszekhanusz** [comment]
Pinging @KingDarBoja

**Comment by bollwyvl** [comment]
> how we can proceed.

I'll be following up on the conda-forge side once a release goes out with #311 in it. I'll ensure that it runs `pip check` and the test suite under coverage with a threshold, which is usually good enough for enable automerge.

when i get that working, I can ping you: it's always good to have upstream-aware maintainers around! you'd just need to comment that you'd like to be a maintainer, and get added to a file.

if the existing maintainers are unresponsive (life happens), we can escalate to the conda-forge core team, but hopefully it doesn't come to that.

After a PR gets merged adding you as a maintainer, the workload would be:
- wait for a notification about a bot making a PR after a pypi release
  - if it's auto-merge, and everyhting's green, then there's nothing to do
- if dependencies changed or tests failed
  - change a few lines of yaml
  - type a comment on a PR
- repeat until :heavy_check_mark: 
- press a button on PR

**Comment by bollwyvl** [comment]
#311 is now in, so when the next release goes out, i'll work on overhauling the conda-forge build.

**Comment by leszekhanusz** [comment]
[Version 3.2.0](https://github.com/graphql-python/gql/releases/tag/v3.2.0) is now released.

**Comment by bollwyvl** [comment]
[That PR](https://github.com/conda-forge/gql-feedstock/pull/12) was merged, and should be available within an hour or two on CDN: feel free to open another issue to propose another maintainer.

**Comment by leszekhanusz** [comment]
Great!

**Comment by motybz** [comment]
Thank you very much, it works.
I think it is worth writing in the documentation that extra dependencies not included in the conda package installation recipe (like websocket)

**Comment by bollwyvl** [comment]
>
> Yeah, conda lacks extras, the best we have are run_constrained, which we
use to honor at least extras that have version constraints.

To actually light up the dependencies, we build a bunch of metapackages
e.g. graphql-with-websockets. They are all listed on the graphql-feedstock
github page, but not the anaconda.org page for graphql, but would be found
by search.

It's hard to be too sad about not having extras, given the issues they
present: they aren't discoverable on pypi (at all) or locally, short of
reading the setup data, and user+selected ones aren't honored in later
resolves.

**Comment by leszekhanusz** [comment]
I added some documentation on PR #321
