### ISSUE TITLE
Thread-safety for gql.Client

### ISSUE THREAD

**Issue by timbrnbrr** [graphql-python/gql#314]
We are using a multi-threaded Flask server with Plotly Dash as framework and the Gql package to communicate with our Graphene backend-api. We have encountered a problem when using `gql.transport.requests.RequestsHTTPTransport` in a multi-threaded environment. Here's a minimal example for this odd behaviour:

```
from urllib.parse import urljoin
from gql import Client
from gql.dsl import DSLSchema, DSLQuery, dsl_gql
from gql.transport.requests import RequestsHTTPTransport
from threading import Thread, Lock

transport = RequestsHTTPTransport(url=urljoin('http://127.0.0.1:8081/', 'graphql'), verify=True, retries=3)
gql_client = Client(transport=transport, fetch_schema_from_transport=True)


with gql_client as session:
    ds = DSLSchema(gql_client.schema)


def get_users():
    with gql_client as session:
        query = dsl_gql(
            DSLQuery(
                ds.Query.Users.select(
                    ds.User.UserId,
                    ds.User.FirstName,
                    ds.User.LastName,
                    ds.User.Mail
                )
            )
        )

        res = session.execute(query)
        print(res)
    return res['Users']


Thread(target=get_users).start()
Thread(target=get_users).start()
```

This leads to the following exception: `gql.transport.exceptions.TransportAlreadyConnected: Transport is already connected`
The reason for this is, that one thread is trying to call `connect()` on the transport object when calling `with gql_client as session:`, although it is already connected by another thread. To ensure thread-safety when using Gql, we implemented the following wrapper class using `gql.Client` as base class:

```
from gql import Client
from threading import Lock

class ThreadsafeGqlClient(Client):
    def __init__(
            self,
            schema=None,
            introspection=None,
            transport=None,
            fetch_schema_from_transport=False,
            execute_timeout=10,
            serialize_variables=False,
            parse_results=False
    ):
        super().__init__(
            schema=schema,
            introspection=introspection,
            transport=transport,
            fetch_schema_from_transport=fetch_schema_from_transport,
            execute_timeout=execute_timeout,
            serialize_variables=serialize_variables,
            parse_results=parse_results
        )
        self._lock = Lock()

    def __enter__(self):
        self._lock.acquire()
        return super().__enter__()

    def __exit__(self, *args):
        super().__exit__(args)
        self._lock.release()
```

This way, we are able to make sure that a thread waits for using the client object until another thread is finished using it.

We know that there's also the gql asyncio approach using `gql.transport.aiohttp.AIOHTTPTransport`, but we've learned that it is not recommended to combine a multi-threaded flask-server with asyncio (see https://stackoverflow.com/questions/67206119/asyncio-run-dash-flask-server-with-another-coroutine-concurrently).

It would be nice if the gql could handle multiple threads accessing the client object on its own in the future, also when `RequestsHTTPTransport` is used. What is your opinion on this?

**Comment by leszekhanusz** [comment]
When you run `with gql_client as session:`, the gql client makes a connection to the backend with the provided transport.
With each transport and client, you can have only one connection opened at a time.
Using a lock like you do may be an acceptable solution but you may lock threads unnecessarily when a connection is happening on one of the threads.
A better solution would be to have a different client for each Thread, this way each thread would be able to make connections independently and would not have to wait for the other connections to finish before making another one.


It would look like something like this:

```python

gql_clients = []

for i in range(2):
    transport = RequestsHTTPTransport(url=urljoin('http://127.0.0.1:8081/', 'graphql'), verify=True, retries=3)
    gql_clients[i] = Client(transport=transport, fetch_schema_from_transport=True)
    
def get_users(gql_client):
    ...
    
Thread(target=get_users, args=(gql_clients[0],)).start()
Thread(target=get_users, args=(gql_clients[1],)).start()
    
```

Then you might also want to fetch the schema from transport using only the first client and provide the schema to the other clients with the `schema` arg of Client.

Yet another option would be to modify your `ThreadsafeGqlClient` so that instead of locking, it will provide a pool of available gql clients or even create another client on the fly if needed.

**Comment by timbrnbrr** [comment]
Hi, thanks for your prompt reply and solution approach.

We have implemented a connection pool based solution as suggested and want to share it. We are using `queue.Queue` as pool to store clients. The benefit of this data structure is that the thread accessing it will block when trying to get a client object until a client object is available again. This way, we can initially provide any number of clients and make sure that the threads will use them in a thread-safe and efficient way.


```
from urllib.parse import urljoin
from gql import Client
from gql.dsl import DSLSchema, DSLQuery, dsl_gql
from gql.transport.requests import RequestsHTTPTransport
from threading import Thread
import queue

class GqlClientConnectionPool:
    def __init__(self, url, pool_size=2):
        self._url = url
        self._queue = queue.Queue()

        transport = RequestsHTTPTransport(url=url, verify=True, retries=3)
        client = Client(transport=transport, fetch_schema_from_transport=True)

        with client as session:
            self.schema = DSLSchema(client.schema)

        for i in range(pool_size):
            transport = RequestsHTTPTransport(url=self._url, verify=True, retries=3)
            client = Client(transport=transport, fetch_schema_from_transport=False)
            self._queue.put(client)

    def execute(self, query):
        client = self._queue.get()
        with client as session:
            resp = session.execute(query)
        self._queue.put(client)

        return resp


gql_pool = GqlClientConnectionPool(url=urljoin('http://127.0.0.1:8081/', 'graphql'))


def get_users():
    ds = gql_pool.schema
    query = dsl_gql(
        DSLQuery(
            ds.Query.Users.select(
                ds.User.UserId,
                ds.User.FirstName,
                ds.User.LastName,
                ds.User.Mail
            )
        )
    )

    res = gql_pool.execute(query)
    print(res)
    return res['Users']


Thread(target=get_users).start()
Thread(target=get_users).start()
Thread(target=get_users).start()
Thread(target=get_users).start()
```

**Comment by leszekhanusz** [comment]
Looks clean!
A small optimization you can still make if your query does not change during execution is to generate the query (the `dsl_gql` call) outside of the `get_users` method so that it is not recreated each time you call the method.

**Comment by leszekhanusz** [comment]
Also you may want to add try-catch blocks in your execute method so that if there was a problem with a connection it will only affect the current Thread and will work again if the connection problems are solved.
