### ISSUE TITLE
GQL api error , Something went wrong while executing your query. Please include `1E76:2573:409BEA:47312D:626A4C07` when reporting this issue

### ISSUE THREAD

**Issue by dsharma522** [graphql-python/gql#323]
While fetching the USERS from gql api, it says the error 
```
Something went wrong while executing your query. Please include `1E76:2573:409BEA:47312D:626A4C07` when reporting this issue
```
which does not tells where and what the problem is. 

**To Reproduce**
```gql
query getUserProfile($login: String!) {
          user(login: $login){
                avatarUrl
                bio
                bioHTML
                commitComments {
                  totalCount
                }
                company
                companyHTML
                contributionsCollection {
                  contributionCalendar {
                    totalContributions
                  }
                  totalCommitContributions
                  totalPullRequestContributions
                  totalPullRequestReviewContributions
                  totalIssueContributions
                  totalRepositoryContributions
                }
                createdAt
                databaseId
                id
                login
                name
                organizations {
                  totalCount
                }
                resourcePath
                twitterUsername
                updatedAt
                url
                websiteUrl
              }

          rateLimit {
            remaining
            nodeCount
          }
        }
```
Above is the gql query for fetching the user profile on `https://api.github.com/graphql` with `POST` method (used my access token in header while fetching the data )
The errors comes on various `login` like `notriddle` , `J0WI` , `maxaf` and many more.

The api says above error and the error code in the message get changed every-time which has no clue about the problem , bug.
How and what to interpret the above error message? 

The above error comes in python as well and in the postman too
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/opt/ingestion/peritus/ingestion/adapters/github/github_adapter.py", line 882, in get_user
    user_profile = self.client.get_user_profile(login=user_login)
  File "/opt/ingestion/peritus/ingestion/adapters/github/github_client.py", line 221, in get_user_profile
    data = self.client.execute(query, variable_values=params)
  File "/usr/local/lib/python3.6/site-packages/gql/client.py", line 78, in execute
    raise Exception(str(result.errors[0]))
Exception: {'message': 'Something went wrong while executing your query. Please include `AFC4:2413:61412:64508:626A4190` when reporting this issue.'}
```

**System info (please complete the following information):**
 - OS: macOS Monterey Version 12.3
 - Python version: 3.6 
 - gql version: 2.0.0
 - graphql-core version: 2.0

**Comment by leszekhanusz** [comment]
This is not a `graphql-python/gql` issue. The error comes from GitHub.

I noticed that the logins you have provided are all private, so that might explain why you can't get that info with your query.

You should instead post an issue on [github.community](https://github.community/)

[Here is an example](https://github.community/t/graphql-giving-error-something-went-wrong-while-executing-your-query-please-include-971037/13738) which seems related to your problem.

Note: this is unrelated but you might want to upgrade to gql version 3.2

**Comment by dsharma522** [comment]
Thanks , I have posted in community. There seems to many issue related to GQL unresolved already

**Comment by leszekhanusz** [comment]
Keeping [link here](https://github.community/t/gql-api-error-something-went-wrong-while-executing-your-query-please-include-1e76409bea626a4c07/247605) for reference.
