### ISSUE TITLE
BUG: No module named 'requests_toolbelt'

### ISSUE THREAD

**Issue by wvidana** [graphql-python/gql#327]
**Describe the bug**
The packaged version on pip gives a dependency error on `requests_toolbelt`. This has been happening since January (first time I noticed it was on Jan 26). Any running code gives the error:
```shell
No module named 'requests_toolbelt'
```

It gets fixes if I install that package alongside, but if it is a dependency of `gql` I would assume it to be installed/shipped alongside. NOTE: I use `pipenv`, haven't tried to reproduce just installing `gql` with `pip`.

**To Reproduce**
Import `gql` package with
```python
from gql import gql
from gql.client import Client
from gql.transport.requests import RequestsHTTPTransport
```

The package `requests_toolbelt` is not imported correctly and gives the error `No module named 'requests_toolbelt'`

**Expected behavior**
There should be no import errors on a third party package

**System info (please complete the following information):**
 - OS: docker image `python:3.8-slim` but also happens while running the code on AWS Lambda (I assume some Amazon Linux image)
 - Python version: 3.8
 - gql version: `==3.2.0`
 - graphql-core version: non relevant

**Comment by leszekhanusz** [comment]
Please check the [installation instructions](https://gql.readthedocs.io/en/stable/intro.html#installation) and either install gql with the `all` or the `requests` extra dependency.
