### ISSUE TITLE
Documentation needs an example for paged queries

### ISSUE THREAD

**Issue by davaya** [graphql-python/gql#330]
I have a GraphQL service that runs correctly using GraphiQL.  It defines a paged "listDevices" query using "nextToken" as the cursor, and it returns a "ModelDeviceConnection" connection containing "items" and "nextToken".

![par-list](https://user-images.githubusercontent.com/19152940/169373365-5bcc1926-0bd8-44e8-b103-ee0b255c4465.jpg)

But when I try to run the same query from Python using gql, it gets a syntax error:
```
raise validation_errors[0]
graphql.error.graphql_error.GraphQLError: Cannot query field 'nextToken' on type 'Query'.

GraphQL request:3:11
2 |         query listDevices ($limit: Int) {
3 |           nextToken
  |           ^
4 |           items {

```
The code is:
```
def run_query():
    transport = AIOHTTPTransport(url=PAR_API, headers=PAR_AUTH)
    client = Client(transport=transport, fetch_schema_from_transport=True)
    query = gql(
        """
        query listDevices ($limit: Int) {
          nextToken
          items {
            id
          }
        }
        """
    )
    params = {"limit": 10}
    return client.execute(query, variable_values=params)
```

What is the correct syntax for the gql string argument to return values for nextToken and items?  This is a common pattern that should be documented with an example.

**Comment by leszekhanusz** [comment]
See [Using variables](https://gql.readthedocs.io/en/stable/usage/variables.html) for the documentation.
