### ISSUE TITLE
what's the use of `fetch_schema_from_transport` flag

### ISSUE THREAD

**Issue by Vichoko** [graphql-python/gql#331]
Having this flag as `true` adds a huge instantiation overhead over the `gql.Client`
[In the docs ](https://gql.readthedocs.io/en/latest/modules/client.html#gql.client.Client)isn't clear what's the actual difference between having this flag as `true` or `false`.
So my question is: What's the difference between having this flag or not? 

I understand it's a boolean to indicate if we want to fetch the schema from the transport using an introspection query. But why/how is this useful at all?

**Comment by leszekhanusz** [comment]
If a schema is available, gql will validate the queries locally before sending them to the backend.
This is explained in the [schema validation](https://gql.readthedocs.io/en/stable/usage/validation.html) part of the docs.

You'll also need a schema:

- [to compose queries dynamically with the DSL module](https://gql.readthedocs.io/en/stable/advanced/dsl_module.html)
- [to serialize/parse custom scalars or enums](https://gql.readthedocs.io/en/stable/usage/custom_scalars_and_enums.html)

If you don't want to validate your queries and don't need those two features, then no schema is needed.

Using introspection with `fetch_schema_from_transport=True` can be useful during development when the schema of the backend changes a lot as it ensures that the client always have the latest schema available. Once you're in production, if you need a schema for the reasons above, then you're better to just download the schema and [provide it as a file](https://gql.readthedocs.io/en/stable/usage/validation.html#using-a-provided-schema) in your client.

Feel free to propose a PR to make the docs clearer about this.

**Comment by leszekhanusz** [comment]
> I wonder what is the advantage of locally validating the queries?

Not much, I agree

> I just made some tests to test the validation, and it seems the exceptions raised for invalid queries are the same while validating the schema or not.

Normally you should receive a `GraphQLError` if the validation is done locally and a `TransportQueryError` if the validation is done by the backend.
