### ISSUE TITLE
Allow the definition of a custom json serializer

### ISSUE THREAD

**Issue by jmg-duarte** [graphql-python/gql#332]
Basically, I want to be able to do something like
```py
Client(serializer=orjson.loads, deserializer=orjson.dumps)
```

The `aiohttp.ClientSession` allows for custom serialization so it shouldn't be an hard implementation?
https://docs.aiohttp.org/en/stable/client_reference.html

**Comment by leszekhanusz** [comment]
There was a previous discussion about this in issue #216

The main use case was custom scalars serialization and is solved with the current version of gql so it was closed, but I can see there are other uses for this.

The arguments should be set in the transports and not in the `Client` though.

Feel free to submit a PR with tests.

**Comment by leszekhanusz** [comment]
I looked a bit more about this issue and found out that it is actually possible right now.

you can provide a `client_session_args` argument to the `AIOHTTPTransport` with any additional argument which need to be passed to `aiohttp.ClientSession`, including the `json_serialize` arg:

```python
transport = AIOHTTPTransport(url=url, client_session_args={"json_serialize": json.dumps})
```

**Comment by leszekhanusz** [comment]
In the PR #337 I modified the transport to be simplify it. It can be used like this now:

```python
transport = AIOHTTPTransport(url=url, json_serialize=json.dumps)
```
