### ISSUE TITLE
3.6.8 Support Error.

### ISSUE THREAD

**Issue by cjlaserna** [graphql-python/gql#334]
**Describe the bug**
GQL does not support 3.6.8 because it has multidict as a dependency, and multidict is Python>=3.7 only.

**To Reproduce**
pip install gql on a python 3.6.8 environment

**Expected behavior**
Proper installation

**System info (please complete the following information):**
 - OS: CentOS
 - Python version: 3.6.8

**Comment by leszekhanusz** [comment]
Sorry, I cannot reproduce your problem.

I installed gql with the `all` and the `dev` extra dependencies on a clean Python 3.6.13 environment and all the tests are passing without problem.

Are you sure you installed gql correctly following [the installation instructions](https://gql.readthedocs.io/en/stable/intro.html#installation), with the required transport dependencies?

For reference you can find below a `pip list` showing all the versions of the dependencies installed. multidict has version 5.2.0

[pip list](https://github.com/graphql-python/gql/files/9033173/pip_list.txt)
