### ISSUE TITLE
gql-cli command not found

### ISSUE THREAD

**Issue by florian-guily** [graphql-python/gql#339]
**Common problems**
- If you receive a TransportQueryError, it means the error is coming from the backend (See [Error Handling](https://gql.readthedocs.io/en/latest/advanced/error_handling.html)) and has probably nothing to do with gql
- If you use IPython (Jupyter, Spyder), then [you need to use the async version](https://gql.readthedocs.io/en/latest/async/async_usage.html#ipython)
- Before sending a bug report, please consider [activating debug logs](https://gql.readthedocs.io/en/latest/advanced/logging.html) to see the messages exchanged between the client and the backend

**Describe the bug**
When trying to use the cli, i'm getting the command not found error

**To Reproduce**
pip install gql[all]
gql-cli --version

**Expected behavior**
Version number of gql-cli

**System info (please complete the following information):**
 - OS: ubuntu 20.04 on wsl 2 (windows subsystem)
 - Python version: 3.8.10
 - gql version: 3
 - graphql-core version:3.3

**Comment by leszekhanusz** [comment]
I just tried it on wsl and when I run `pip install gql[all]`, the following warning message appears:

```
  WARNING: The script normalizer is installed in '/home/leszek/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script gql-cli is installed in '/home/leszek/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

After adding .local/bin to the PATH, it works correctly:

```
~$ export PATH="$PATH:/home/leszek/.local/bin"
leszek@DESKTOP-ULDB3LC:~$ gql-cli --version
v3.3.0
```
