### ISSUE TITLE
Fails to honour HTTPS_PROXY environment variable

### ISSUE THREAD

**Issue by jonathan-boudreau-work** [graphql-python/gql#342]
**Describe the bug**
`gql` does not handle proxy usage when using the asyncio API. Other libraries such as httpx support this out of the box by honouring the HTTPS_PROXY / HTTP_PROXY environment variable.

**To Reproduce**
- deploy a squid proxy.
- set the HTTPS_PROXY variable to that corresponding proxy
- make a graphql request to github

**Expected behavior**
The request goes through the proxy. We block all outgoing network requests that don't go through the proxy, so this means we get a timeout when making graphql requests.

**System info (please complete the following information):**
 - OS: debian
 - Python version: 3.8
 - gql version: 3.3.0
 - graphql-core version: 3.2.1

ps. Alternatively, this could be addressed by supporting async httpx.

**Comment by leszekhanusz** [comment]
Does it solve your problem?

**Comment by huyz** [comment]
Seems to me that `trust_env` should be set to `True` by default for `gql-cli` since it's just a development tool and not deployed.
