### ISSUE TITLE
Setting execution timeout with gql-cli

### ISSUE THREAD

**Issue by gonzalezzfelipe** [graphql-python/gql#347]
**Describe the bug**

There is a default `execution_timeout` on the client, which can't be modified on the CLI. This means that any request that lasts more than 10 seconds that is done using the `gql-cli` will fail, and there's nothing the user can do about it. It is possible to add the possiblity to modify this timeout using the CLI arguments, but why have the default timeout at all? I don't see any gain imposing a timeout on the users.

Refferences in the code:

* Default execution timeout in client: https://github.com/graphql-python/gql/blob/master/gql/client.py#L78
* Usage of the client on the CLI: https://github.com/graphql-python/gql/blob/master/gql/cli.py#L369-L371

**System info (please complete the following information):**
 - OS: MacOs
 - Python version: 3.10.4
 - gql version: 3.4.0
 - graphql-core version: 3.2.1

**Comment by leszekhanusz** [comment]
Hmm it seems we did the same PR at the same time...

Adding arguments to gql-cli can be done.

Removing the timeout is not an option and increasing the default would be a breaking change and I don't see the point if it is configurable.
