### ISSUE TITLE
Add an example to connect to Phoenix Channel

### ISSUE THREAD

**Issue by harigopalakrishna** [graphql-python/gql#352]
Could we please add an example that shows how to use `PhoenixChannelWebsocketsTransport` . I'm trying to connect to the websocket server implemented using Phoenix Channel and unable to do so by following the documentation. Any help would be greatly appreciated.

**Comment by leszekhanusz** [comment]
There are some examples [in the tests](https://github.com/graphql-python/gql/blob/master/tests/test_phoenix_channel_query.py#L52).

What is your backend, it it public ?

**Comment by harigopalakrishna** [comment]
@leszekhanusz Thanks for your quick response. Our backend is Phoenix/Elixir, and I'm trying to connect to the [channels](https://hexdocs.pm/phoenix/channels.html).  It is not a public project. I'll look in to the test, appreciate the reference.
