### ISSUE TITLE
Am i able to mock response with gql?

### ISSUE THREAD

**Issue by Mimezzz** [graphql-python/gql#356]
I am trying to do some unit tests and i used requests_mock.

I got an error "Invalid or incomplete introspection result. Ensure that you are passing the 'data' attribute of an introspection response and no 'errors' were returned alongside"

i searched for mock test instructions in the doco but cant find anything. i found with graphine one seemed to be able to mock a test by patching it. Not sure if there is a go-to solution with this client?

**Comment by Mimezzz** [comment]
i found the issue with with fetch_schema_from_transport=True, as it's not really connecting to the endpoint it could not fetech the schema hence not able to pass the introspection. however, does nayone know how i can mock a schema?

**Comment by leszekhanusz** [comment]
There was a previous discussion about testing with mock in PR #193
What exactly do you want to mock? Could you post an example?

**Comment by Mimezzz** [comment]
thanks!@leszekhanusz it's a very basic function, 

```
def api_func()
headers = {
            "Authorization": f"{self.__token_type} {self.__access_token}",
            "Content-Type": "application/json"
        }
        query = load_query("/path/to/graphql query.graphql")
        variable = {"variable": id}

        transport = RequestsHTTPTransport(url=f"{self.base_url}/query", headers=headers)
        client = Client(transport=transport, fetch_schema_from_transport=True)

        def execute(query, variable):
            try:
                response = client.execute(query, variable_values=variable)
                return  json.loads(json.dumps(response))

            except Exception as e:
                log.error(f"API error: {e}")

        result = execute(query, variable=variable)
        return result
```

i wanted to mock post to 1. authentification (worked ok), 2. graphql(not working if i continued to undefine schema and asked to fetch schema from transport. I don't have permission to print schema either so not able to give a pre-defined schema here).

my test is structured like:
`def test_api_func(api_client):
    with requests_mock.Mocker() as mock:
        mock.post("https://xxx/token", json=MOCK_AUTH_RESPONSE)
        mock.post("https://xxx/query", json=MOCK_API_RESPONSE)
        id="1234"

        results = api_client.api_func(id)
        assert results ==  MOCK_PROPERTY_SEARCH_RESPONSE.get("data")
`

**Comment by Mimezzz** [comment]
i have fixed this issue with the help of patch. 

`with patch('xxx.RequestsHTTPTransport') as gql_transport_mock:
        with patch('xxx.Client') as gql_client_mock:
            with requests_mock.Mocker() as mock:
                mock.post("https://xxxxx/token, json=MOCK_AUTH_RESPONSE)
                mock.post("https://xxx/query", json=MOCK_RESPONSE)

                gql_transport_mock.return_value = Mock()

                gql_client_instance = gql_client_mock.return_value

                gql_client_instance.execute.return_value = MOCK_RESPONSE

                result = client.function(variable)
                # assert
                assert result == {"request_body": None, "response_body": MOCK_RESPONSE}`
