### ISSUE TITLE
HTTPX transport installation with conda

### ISSUE THREAD

**Issue by leszekhanusz** [graphql-python/gql#372]
httpx support is available in the [pre-release 3.5.0b0](https://github.com/graphql-python/gql/releases/tag/v3.5.0b0).

We should be able to install gql with `httpx` with conda using `conda install gql-with-httpx`

This will be done once the next stable version of gql is released.

**Comment by bollwyvl** [comment]
Happy to help on this... feel free to make an issue on [the feedstock](https://github.com/conda-forge/gql-feedstock) when these kinds of things are on the horizon. Even better might be to add a co-maintainer who's more abreast of developments. :wink:

**Comment by leszekhanusz** [comment]
It is now possible to install pre-releases with conda.

See issue #441

You can install gql with the httpx transport with conda with the following command:

```
conda install -c conda-forge -c conda-forge/label/graphql_core_alpha -c conda-forge/label/gql_beta gql-with-httpx
```
