### ISSUE TITLE
Performance parsing large schemas

### ISSUE THREAD

**Issue by rposborne** [graphql-python/gql#374]
**Describe the bug**
We are seeing slow client boot times before being able to make queries with times measured in seconds 1-8s
<img width="809" alt="image" src="https://user-images.githubusercontent.com/243989/205333723-ef2ec572-4a35-47b4-9a84-8aaac34a612a.png">

**To Reproduce**
Reproduce follow steps on this gist. 
https://gist.github.com/rposborne/eef63e4c403c137e2135d8ed39d3330e

**Expected behavior**
Parsing the schema should not pose a performance penalty. 

**System info (please complete the following information):**
 - OS: macOS Ventura
 - Python version: 3.9.15
 - gql version: 3.4.0
 - graphql-core version: 3.2.3
 
 **Thankful**
 OSS devs are the backbone of my career, and I am deeply thankful for the time anyone spends evaluating this issue.

**Comment by rposborne** [comment]
Is it considered best practice not to validate the schema in production scenarios?

**Comment by leszekhanusz** [comment]
Using `parse_results=True` is only useful if you have [custom scalars or enums](https://gql.readthedocs.io/en/stable/usage/custom_scalars_and_enums.html) that you want to automatically parse.
I don't see any custom scalar or enum in your schema, so it's probably not needed.

If you don't need a schema and you care about performance, then you don't need to provide the schema to the client. gql works fine without it.

Valid reasons to provide a schema:
 - to validate your queries locally (not necessary in production)
 - to use the DSL module to generate gql queries dynamically
 - for enums/custom scalars serializing and parsing

If a schema is provided, gql will validate it and validate the queries it receives before sending them to the backend.

As for the performance of validating the schema, it depends on the package [graphql-core](https://github.com/graphql-python/graphql-core).

**Comment by rposborne** [comment]
Alright, we are taking the "don't parse the schema in prod" approach to cut the boot time down.   I'll work a more isolated performance ticket over on the upstream package.
