### ISSUE TITLE
thanks for gql!

### ISSUE THREAD

**Issue by denisart** [graphql-python/gql#375]
Hello, thanks for gql. I use it in my python projects with GraphQL.

I created project for pydantic data-model generation from some GraphQL schema.
And for GraphQL queries generation from python classes.
This project based on graphql-core. The project URL is https://github.com/denisart/graphql2python

The special example for use graphql2python with gql: https://denisart.github.io/graphql2python/gql.html

You can see more examples in:
https://github.com/denisart/graphql-query
https://denisart.github.io/graphql2python/model.html

My project so far has few settings. This will be fixed in future releases. 

I hope that the developments in this project can be useful for the gql users.

**Comment by leszekhanusz** [comment]
Thanks.
Sorry I'm closing this as this is not an issue.
