### ISSUE TITLE
Subscriptions - throws an error - when the same graphql document works fine from graphql playground

### ISSUE THREAD

**Issue by cravimvmd** [graphql-python/gql#383]
**Describe the bug**
Here is graphql document for subscription:

subscription {
  count(target: 10)
}

Here is the schema: 
type Subscription {
  count(target: Int! = 100): Int!
}

# Please provide a full stack trace if you have one.
Here is the debug info - 

DEBUG:gql.transport.websockets:connect: starting
DEBUG:websockets.client:= connection is CONNECTING
DEBUG:websockets.client:> GET /graphql HTTP/1.1
DEBUG:websockets.client:> Host: 127.0.0.1:8000
DEBUG:websockets.client:> Upgrade: websocket
DEBUG:websockets.client:> Connection: Upgrade
DEBUG:websockets.client:> Sec-WebSocket-Key: wBfOzFn3XedZlMy80zJA1w==
DEBUG:websockets.client:> Sec-WebSocket-Version: 13
DEBUG:websockets.client:> Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
DEBUG:websockets.client:> Sec-WebSocket-Protocol: graphql-ws, graphql-transport-ws
DEBUG:websockets.client:> User-Agent: Python/3.7 websockets/10.4
DEBUG:websockets.client:< HTTP/1.1 101 Switching Protocols
DEBUG:websockets.client:< Upgrade: websocket
DEBUG:websockets.client:< Connection: Upgrade
DEBUG:websockets.client:< Sec-WebSocket-Accept: XRP247zcCxfx+jd9nzcQVcohdIY=
DEBUG:websockets.client:< Sec-WebSocket-Extensions: permessage-deflate
DEBUG:websockets.client:< Sec-WebSocket-Protocol: graphql-ws
DEBUG:websockets.client:< date: Fri, 03 Feb 2023 15:47:30 GMT
DEBUG:websockets.client:< server: uvicorn
DEBUG:websockets.client:= connection is OPEN
DEBUG:gql.transport.websockets:backend subprotocol returned: 'graphql-ws'
DEBUG:websockets.client:> TEXT '{"type": "connection_init", "payload": {}}' [42 bytes]
INFO:gql.transport.websockets:>>> {"type": "connection_init", "payload": {}}
DEBUG:websockets.client:< TEXT '{"type": "connection_ack"}' [26 bytes]
INFO:gql.transport.websockets:<<< {"type": "connection_ack"}
DEBUG:gql.transport.websockets:connect: done
DEBUG:websockets.client:> TEXT '{"id": "1", "type": "start", "payload": {"query... }\\n    }\\n  }\\n}"}}' [1456 bytes]
INFO:gql.transport.websockets:>>> {"id": "1", "type": "start", "payload": {"query": "query IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n    }\n    mutationType {\n      name\n    }\n    subscriptionType {\n      name\n    }\n    types {\n      ...FullType\n    }\n    directives {\n      name\n      description\n      locations\n      args {\n        ...InputValue\n      }\n    }\n  }\n}\n\nfragment FullType on __Type {\n  kind\n  name\n  description\n  fields(includeDeprecated: true) {\n    name\n    description\n    args {\n      ...InputValue\n    }\n    type {\n      ...TypeRef\n    }\n    isDeprecated\n    deprecationReason\n  }\n  inputFields {\n    ...InputValue\n  }\n  interfaces {\n    ...TypeRef\n  }\n  enumValues(includeDeprecated: true) {\n    name\n    description\n    isDeprecated\n    deprecationReason\n  }\n  possibleTypes {\n    ...TypeRef\n  }\n}\n\nfragment InputValue on __InputValue {\n  name\n  description\n  type {\n    ...TypeRef\n  }\n  defaultValue\n}\n\nfragment TypeRef on __Type {\n  kind\n  name\n  ofType {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}"}}
DEBUG:websockets.client:< TEXT '{"type": "error", "id": "1", "payload": {"messa...ne": 2, "column": 3}]}}' [146 bytes]
INFO:gql.transport.websockets:<<< {"type": "error", "id": "1", "payload": {"message": "The subscription field '__schema' is not defined.", "locations": [{"line": 2, "column": 3}]}}
DEBUG:gql.transport.websockets:In subscribe finally for query_id 1
DEBUG:gql.transport.websockets:listener 1 deleted, 0 remaining
DEBUG:gql.transport.websockets:close: starting
DEBUG:gql.transport.websockets:_fail: starting with exception: TransportClosed('Websocket GraphQL transport closed by user')
DEBUG:gql.transport.websockets:wait_close: starting
DEBUG:gql.transport.websockets:_close_coro: starting
DEBUG:gql.transport.websockets:_close_coro: starting clean_close
DEBUG:websockets.client:> TEXT '{"type": "connection_terminate"}' [32 bytes]
INFO:gql.transport.websockets:>>> {"type": "connection_terminate"}
DEBUG:gql.transport.websockets:_close_coro: sending exception to listeners
DEBUG:gql.transport.websockets:_close_coro: close websocket connection
DEBUG:websockets.client:= connection is CLOSING
DEBUG:websockets.client:> CLOSE 1000 (OK) [2 bytes]
DEBUG:websockets.client:< CLOSE 1000 (OK) [2 bytes]
DEBUG:websockets.client:= connection is CLOSED
DEBUG:gql.transport.websockets:_fail: starting with exception: ConnectionClosedOK(Close(code=1000, reason=''), Close(code=1000, reason=''), False)
DEBUG:gql.transport.websockets:close_task is not None in _fail. Previous exception is: TransportClosed('Websocket GraphQL transport closed by user') New exception is: ConnectionClosedOK(Close(code=1000, reason=''), Close(code=1000, reason=''), False)
DEBUG:gql.transport.websockets:Exiting _receive_data_loop()
DEBUG:gql.transport.websockets:_close_coro: websocket connection closed
DEBUG:gql.transport.websockets:_close_coro: start cleanup
DEBUG:gql.transport.websockets:_close_coro: exiting
DEBUG:gql.transport.websockets:wait_close: done
DEBUG:gql.transport.websockets:close: done
DEBUG:main:load_data_from_subscription Error: {'message': "The subscription field '__schema' is not defined.", 'locations': [{'line': 2, 'column': 3}]}
INFO:     127.0.0.1:44078 - "GET /runsubscription HTTP/1.1" 503 Service Unavailable
If you can, please provide the backend URL, the GraphQL schema, the code you used.

**To Reproduce**

** Here is the code snippet used **
ws_transport = WebsocketsTransport(url='ws://127.0.0.1:8000/graphql')
ws_client = Client(
    transport=ws_transport,
    fetch_schema_from_transport=True,
)
counter = 10
queryCountSubscription = gql( 
'''
    subscription {
        count(target : counter) 
    }   
'''
)

@app.get("/runsubscription", response_class=HTMLResponse)
async def load_data_from_subscription():
     try:
        async with ws_client as session:
            async for result in session.subscribe(queryCountSubscription):
                print (result)
     except Exception as e:
        log.debug(f"load_data_from_subscription Error: {e}")
        raise HTTPException(status_code=503, detail="GraphQL Subscription call failed!")

     return f"""
    <html>
        <head>
            <title>Run Subscription</title>
        </head>
        <body>
  <pre id="runsubscription" ></pre>
  <script>
    document.getElementById("runsubscription").innerHTML = JSON.stringify({result}, null, 4); 
  </script>
 </body>
</html>
"""

**Expected behavior**
Please take a look at the expected response in a graphql playground - image attached.
A sample single response.
 {
  "data": {
    "count": 2
  }
} 

![expected-output](https://user-images.githubusercontent.com/117669536/216649399-2ccdf4d7-15ed-4cdb-8bb3-7e5960fdfb3c.png)

**System info (please complete the following information):**
 - OS: Amazon Linux
 - Python version: 3.7+
 - gql version: This was installed -$ pip3 install gql[all]
 - graphql-core version:

**Comment by cravimvmd** [comment]
Looks like a JSON - DocumentNode - submission issue. The /tests have what seems to be a work around. Please provide an example on how it can be used, thanks.

**Comment by leszekhanusz** [comment]
When you use `fetch_schema_from_transport=True`, the first query sent to the server will be an Introspection query to detect the schema.
In your case it seems the server does not support receiving introspection queries on this endpoint and it sent an error.
gql received the error and threw it as a TransportQueryError.

Try without `fetch_schema_from_transport=True` and the first query sent will be your subscription.

**Comment by cravimvmd** [comment]
Thanks Lezek! 

That suggestion worked. 

The server being used is Strawberry.
