### ISSUE TITLE
transport.request.connect should be idempotent

### ISSUE THREAD

**Issue by majidaldo** [graphql-python/gql#387]
https://github.com/graphql-python/gql/blob/05c05a2272351d3eaa9f8bf607c683d208d100bd/gql/transport/requests.py#L106

is there a reason for raising an exception if it's already connected?!  (sorry for what may be ignorance)

i want to use my own session.

**Comment by leszekhanusz** [comment]
It should help users detecting that they have a bug somewhere.
You could [suppress](https://docs.python.org/3/library/contextlib.html#contextlib.suppress) that exception but I would advice instead to modify your code so that the connect is called only once.

**Comment by leszekhanusz** [comment]
If you're willing to use the AIOHTTPTransport async version, then you can have a [permanent async session](https://gql.readthedocs.io/en/stable/advanced/async_permanent_session.html).

**Comment by leszekhanusz** [comment]
There is also the possibility to [manage an aiohttp session yourself](https://github.com/graphql-python/gql/issues/381), but it is not yet in a gql release.

**Comment by majidaldo** [comment]
i went ahead and created my own `Transport` based on `RequestsHTTPTransport`.
```
import requests_cache
# global install
# could do this                                                                                                need post
#requests_cache.install_cache('http_cache', allowable_methods={'GET', 'HEAD', 'POST'})

from gql.transport.requests import RequestsHTTPTransport
from requests.adapters import HTTPAdapter, Retry
from gql.transport.exceptions import TransportAlreadyConnected
class CachedRequestHTTPTransport(RequestsHTTPTransport):

    def connect(self):
        if self.session is None:
            # Creating a session that can later be re-use to configure custom mechanisms
            self.session = requests_cache.CachedSession(
                cache_name='http_cache',
                allowable_methods={'GET', 'HEAD', 'POST'}) # default transport method is post
            # If we specified some retries, we provide a predefined retry-logic
            if self.retries > 0:
                adapter = HTTPAdapter(
                    max_retries=Retry(
                        total=self.retries,
                        backoff_factor=0.1,
                        status_forcelist=[500, 502, 503, 504],
                        allowed_methods=None,
                    )
                )
                for prefix in "http://", "https://":
                    self.session.mount(prefix, adapter)
        else:
            raise TransportAlreadyConnected("Transport is already connected")

    def xconnect(self):
        if self.session is None:
            self.session = requests_cache.CachedSession('http_cache')
```

**Comment by majidaldo** [comment]
still, the Transport args all went into creating the session object. it could be passed in by the user.

**Comment by leszekhanusz** [comment]
Not all, but yes, I get your point.
