### ISSUE TITLE
Sending Graphql queries using RequestsHTTPTransport works, whereas AIOHTTPTransport doesn't work

### ISSUE THREAD

**Issue by HJA24** [graphql-python/gql#388]
**Describe the bug**
When I run a Graphql query using `AIOHTTPTransport` it results in a 503 error. When I run the same query using `RequestsHTTPTransport` I get no error.

```
import asyncio
from gql import Client, gql
from gql.transport.aiohttp import AIOHTTPTransport
from gql.transport.requests import RequestsHTTPTransport


URL = 'https://orchestrator.pgatour.com/graphql'
X_API_KEY = 'da2-gsrx5bibzbb4njvhl7t37wqyl4'


http_headers = {'accept-encoding': 'gzip, deflate, br',
                'accept-language': 'en-US,en;q=0.9',
                'content-length': '251',
                'content-type': 'application/json',
                'origin': 'https://www.pgatour.com',
                'referer': 'https://www.pgatour.com/',
                'sec-ch-ua': 'Chromium;v=110, Not A(Brand;v=24, Google Chrome;v=110',
                'sec-ch-ua-mobile': '?0',
                'sec-ch-ua-platform': 'Windows',
                'sec-fetch-dest': 'empty',
                'sec-fetch-mode': 'cors',
                'sec-fetch-site': 'same-site',
                'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36',
                'x-amz-user-agent': 'aws-amplify/3.0.7',
                'x-api-key': f'{X_API_KEY}',
                'x-pgat-platform': 'web'}

async def get_aynsc_player_odds(pid: int, tid: str) -> None:
    transport = AIOHTTPTransport(url=URL,
                                 headers=http_headers)

    async with Client(
        transport=transport,
        fetch_schema_from_transport=False
    ) as session:
      query = gql(
          f"""
          query {{
              playerOdds(
                  playerId: "{pid}"
                  tournamentId: "{tid}"
              ) {{
              oddsMessage {{
                  header
                  }}
              playerOddsMarkets {{
                  id
                  }}
              }}
          }}
      """)

        result = await session.execute(query)
        print(result)

def get_player_odds(pid: int, tid: str) -> None:
    transport = RequestsHTTPTransport(url=URL,
                                      headers=http_headers,
                                      verify=True)

    client =  Client(transport=transport,
                     fetch_schema_from_transport=False)
    query = gql(
        f"""
        query {{
            playerOdds(
                playerId: "{pid}"
                tournamentId: "{tid}"
            ) {{
            oddsMessage {{
                header
                }}
            playerOddsMarkets {{
                id
                }}
            }}
        }}
    """)

    result = client.execute(query)
    print(result)


# odds = asyncio.run(get_aynsc_player_odds(pid=46970, tid='R2023007'))
get_player_odds(pid=46970, tid='R2023007')
```

**Expected behavior**
The output of the AIOHTTPTransport script should be as follows:

> {'playerOdds': {'oddsMessage': {'header': 'Odds are unavailable'}, 'playerOddsMarkets': []}}

However, the following error is raised:

> concurrent.futures._base.TimeoutError

**System info (please complete the following information):**
 - OS: 12.3.1
 - Python version: 3.7
 - gql version: 3.4.0
 - graphql-core version: 3.2.3

**Comment by leszekhanusz** [comment]
Please provide the full stack trace of the error.

**Comment by HJA24** [comment]
> Traceback (most recent call last):
>   File "/Users/huibmeulenbelt/PycharmProjects/golf/golf/scripts/shotlink/graphql/player_odds.py", line 84, in <module>
>     asyncio.run(get_aynsc_player_odds(pid=46970, tid='R2023007'))
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
>     return loop.run_until_complete(main)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
>     return future.result()
>   File "/Users/huibmeulenbelt/PycharmProjects/golf/golf/scripts/shotlink/graphql/player_odds.py", line 53, in get_aynsc_player_odds
>     result = await session.execute(query)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gql/client.py", line 1226, in execute
>     **kwargs,
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gql/client.py", line 1133, in _execute
>     self.client.execute_timeout,
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 419, in wait_for
>     raise futures.TimeoutError()
> concurrent.futures._base.TimeoutError

**Comment by leszekhanusz** [comment]
By default there is a timeout of 10 seconds to execute queries with async transports.

You can modify this value by passing an `execute_timeout` argument to the `Client`.

```python
client = Client(transport=transport, execute_timeout=60)
```

**Comment by HJA24** [comment]
@leszekhanusz Yes, now I am getting the error after 60 seconds. But I would like to know why the `RequestsHTTPTransport`-version is working and the `AIOHTTPTransport`-version is not working (giving a timeout error)

**Comment by leszekhanusz** [comment]
How long does it take with `RequestsHTTPTransport`? More than 60 seconds?

**Comment by HJA24** [comment]
No, max 10 seconds

**Comment by leszekhanusz** [comment]
I just tried and found out it works if you remove the `content-length` http header. Probably that `requests` will overwrite that header with the correct value while `aiohttp` will keep the value you specified, which is probably incorrect.

**Comment by HJA24** [comment]
indeed, that was the problem! Thanks
