### ISSUE TITLE
gql[all] errors on zsh as it tries to expand [all]

### ISSUE THREAD

**Issue by pedromprado** [graphql-python/gql#389]
It's just a small issue on the README. I had to use double quotes to install the modules.
Using python3's pip3:

`pip3 install "gql[all]"`

HTH,
Pedro

**Comment by aalmazan** [comment]
`zsh` does this by default and this isn't really the problem of this library. Some background info on what `zsh` does: https://unix.stackexchange.com/a/68748

You can disable this behavior by using `setopt` and finding the right option (I personally don't know), but that can have other implications and quoting (IMO) is much easier to remember.

**Comment by pedromprado** [comment]
Sure, it's really not a problem with the library - I just thought I'd tip that to perhaps include in the README. Thanks!
