### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by aalmazan** [graphql-python/gql#390]
Is there any chance we can get a release/pre-release published? I currently have a package pointed to the current master commit (need the content type fix), but it seems that PyPI doesn't allow references to commits to be published. Is there a chance we can get a minor publish out?

**Comment by leszekhanusz** [comment]
Sure! 

[pre-release v3.5.0b1](https://github.com/graphql-python/gql/releases/tag/v3.5.0b1) is now available.

**Comment by aalmazan** [comment]
Thank you again @leszekhanusz for the quick response!
