### ISSUE TITLE
RuntimeError: async generator ignored GeneratorExit

### ISSUE THREAD

**Issue by Jonas1312** [graphql-python/gql#394]
Hi,

When I run this code:
```python
gql_ws_transport = WebsocketsTransport(
    url=self.ws_endpoint,
    headers=self.headers,
    subprotocols=[WebsocketsTransport.APOLLO_SUBPROTOCOL],
    init_payload={
        "headers": {"Accept": "application/json", "Content-Type": "application/json"},
        "Authorization": f"X-API-Key: {self.api_key}",
    },
)
gql_ws_client = Client(
    transport=gql_ws_transport, fetch_schema_from_transport=True
)

subscription = gql_ws_client.subscribe(MY_GRAPHQL_QUERY, variables)

for result in subscription:
    should_break = do_something()
    if should_break:
        subscription.close()
```

I get an error in the console:
```
Exception ignored in: <async_generator object Client.subscribe_async at 0x7f9858ee77a0>
RuntimeError: async generator ignored GeneratorExit
```

How can I break the loop without having this error printed out?

Thanks!

**System info:**
 - OS: macos
 - Python version: 3.7
 - gql version: 3.4.0
 - graphql-core version: 3.2.3

**Comment by leszekhanusz** [comment]
The normal way to exit is simply to use break:

```python
for result in subscription:
    should_break = do_something()
    if should_break:
        break
```

but the same error appears on version 3.4.0, this is a bug.

I've made the PR #395 which should solve this.

**Comment by leszekhanusz** [comment]
It should be fixed in the [pre-release v3.5.0b3](https://github.com/graphql-python/gql/releases/tag/v3.5.0b3)

**Comment by Jonas1312** [comment]
I tested the pre-release and it seems to have fixed the bug. Thanks a lot!

**Comment by NikitaMishin** [comment]
It is possible to trigger unsubscription indirectly (not inside the loop)?
This is quite important if the events on the stream are not frequent.

**Comment by NikitaMishin** [comment]
@leszekhanusz

**Comment by leszekhanusz** [comment]
@NikitaMishin It should be possible in sync mode by calling `.close()` from another thread but a better idea would be to use the async mode and run a subscription inside a task. Once you don't need the subscription anymore you can cancel the task. See [advanced usage](https://gql.readthedocs.io/en/stable/advanced/async_advanced_usage.html) for an example.
