### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by akhilputhiry** [graphql-python/gql#397]
Hi Folks

Sorry for spamming github issues

I need to retrieve the response headers after executing a gql query
My code looks like the following

```
transport = RequestsHTTPTransport(url=self.url, headers=self.headers, retries=3)
client = Client(transport=transport, fetch_schema_from_transport=True)
response = client.execute()
```

currently I am getting the `data` in response
I want to access the `x-request-id` send in the response and use it to log

Could some one please point me in the right direction

**Comment by leszekhanusz** [comment]
The response headers are in [transport.response_headers](https://gql.readthedocs.io/en/stable/usage/headers.html).
