### ISSUE TITLE
Too described logging on transport level.

### ISSUE THREAD

**Issue by mangin** [graphql-python/gql#400]
Hey there,
I think we have a problem here:
https://github.com/graphql-python/gql/blob/master/gql/transport/aiohttp.py#L333

We writes too many logs on info level.
Maybe we should log them only on debug level?

I know that it's possible to tune it on application level.
But still for me it's a real big surprise that gql library writes so many logs by default.

WDYT?

**Comment by mangin** [comment]
https://github.com/graphql-python/gql/pull/401

**Comment by leszekhanusz** [comment]
Sorry, this can't be changed as it is a breaking change.
See [Disabling-logs](https://gql.readthedocs.io/en/stable/advanced/logging.html#disabling-logs) in the docs to modify the log level for gql.

**Comment by mangin** [comment]
Maybe we can change it in the future releases?

now it's a really verbose. And i don't think that everyone knows how to disable logs and would find this article.
Thank you for your reply:

But it could create some problem for production systems. Because now this module generates a lot of logs => someone pays for it => wasting of planet resources (it's a small joke already)

P.S. for my-own project I already disabled it. But yep it's the first library in my life that  logs all traffic by default.
