### ISSUE TITLE
mTLS authentication

### ISSUE THREAD

**Issue by peppermintea** [graphql-python/gql#411]
Hello,

Does gql support mTLS ?

This is an example with requests library:
https://requests.readthedocs.io/en/latest/user/advanced/#client-side-certificates

Thank you!

**Comment by leszekhanusz** [comment]
Any extra argument passed to the [RequestsHTTPTransport init (kwargs)](https://gql.readthedocs.io/en/stable/modules/transport_requests.html#gql.transport.requests.RequestsHTTPTransport) will be passed to the [request method of the requests session](https://github.com/psf/requests/blob/2ad18e0e10e7d7ecd5384c378f25ec8821a10a29/requests/sessions.py#L500).

So you should be able to use client certificates by filling the `cert` argument in the transport:
```
transport = RequestsHTTPTransport(
    url="https://countries.trevorblades.com/",
    cert= ('/path/client.cert', '/path/client.key'),
)
```

**Comment by leszekhanusz** [comment]
Also if your backend supports websockets and also supports doing queries and mutations on the websocket endpoint, then it could be better to use the websockets transport which [can be configured for client certificates](https://gql.readthedocs.io/en/stable/transports/websockets.html#websockets-ssl).

**Comment by peppermintea** [comment]
Thanks!
