### ISSUE TITLE
Possible issue deserializing json to dict

### ISSUE THREAD

**Issue by kstech-roadie** [graphql-python/gql#419]
In a mutation representing an authentication query, i'm getting back a dict from client.execute_async() that looks good all except one thing. The value for the token is the expected JWT but its wrapped in b'' (literally the string "b'eyJ0eXAiOiJKV1QiLxJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODYxMjc1OTMsInN6YiI6InNjaGVkLXFhLWRyaXZlckByb8ekaWUudXMifk.ijKO8nQBKfkP5TPecxhTsFmhA7PNfze_4yQbRAZgXsY'"). So it seems like bytes are being simply cast to str somewhere instead of decoded. Unfortunately I am not at liberty to share the details of the schema or url as this is my employers property and I'm under NDAs.
 - OS: MacOS 13.1
 - Python version: 3.11.2
 - gql version: 3.5.0b4
 - graphql-core version: 3.3.0a3

**Comment by leszekhanusz** [comment]
Which transport are you using?
Try to [enable debug logs](https://gql.readthedocs.io/en/stable/advanced/logging.html#logging) and check if the raw value received from the backend is different.

**Comment by kstech-roadie** [comment]
Thank you for responding. I did that thing where I reach out for help and then immediately solve the problem 😂  Isolated the issue to another part of the code base.
