### ISSUE TITLE
Load request from file

### ISSUE THREAD

**Issue by annndruha** [graphql-python/gql#422]
The concept of graphql involves writing large but precise queries. Which are inconvenient to write as lines in the code. Many implementation of gql clients has a file-store queries as well as extensions for IDEs support syntax highlighting for `.graphql` and `.gql` files.

Feature request: add function for easy load query from `.graphql` or `.gql` files.

For example, add optional parameter `file_patch` in [gql](https://gql.readthedocs.io/en/stable/modules/gql.html#gql.gql) (or file-like object), or create a separate function to load.

Implementation is also simple like this:
```python
# https://github.com/graphql-python/gql/blob/master/gql/gql.py
def gql_from_file(file_path: str) -> DocumentNode:
      with open(file_path) as f:
          return gql(f.read())

# Call
from gql import gql_from_file
doc_node = gql_from_file('some_query.graphql')
```
I will be glad to make a pull request after the discussion :)

**Comment by leszekhanusz** [comment]
Sorry, reading a file is a standard Python feature and I don't see the point of integrating it in gql.

It's the same with [reading the GraphQL schema](https://gql.readthedocs.io/en/stable/usage/validation.html#using-a-provided-schema) which requires the user to use the `open` method himself to read the file (or any other way to read a file in Python)

[The best code is no code at all!](https://blog.codinghorror.com/the-best-code-is-no-code-at-all/)
