### ISSUE TITLE
Websockets 11 Support

### ISSUE THREAD

**Issue by alanhdu** [graphql-python/gql#423]
Hi! right now, `gql` pins its websockets support to `<11` -- do you know how much work it'd be to upgarde support for websockets 11? Judging from the changelog (https://websockets.readthedocs.io/en/stable/project/changelog.html#id7), it looks like the change should be quite manageable, especially since I don't think `gql` uses the sans-IO implementation (I might be wrong about that though!).

**Comment by leszekhanusz** [comment]
It should work fine.
All the tests are passing without any changes needed.

The modification was made in PR #424
