### ISSUE TITLE
Querying an Interface with the DSL

### ISSUE THREAD

**Issue by jscheel** [graphql-python/gql#426]
This may be possible already, but I can't work out how to query an interface with the DSL. For example, how would I implement this query?

```
query Conversation($id: ID!) {
    node(id: $id) {
        ... on Conversation {
            __typename
            id
            subject
        }
    }
}
```

**Comment by leszekhanusz** [comment]
Well, it depends on your schema.

Did you check the [documentation](https://gql.readthedocs.io/en/stable/advanced/dsl_module.html)?

What did you try?

**Comment by jscheel** [comment]
@leszekhanusz Lol, you know what? I had 4 different tabs of the the documentation open, and somehow still missed the Inline Fragment section. That's what I get for starting something new on a Friday afternoon 🤦
