### ISSUE TITLE
DSL how to select fields which are Python reserved keywords

### ISSUE THREAD

**Issue by FrankC01** [graphql-python/gql#462]
Here is the problem I face, I can create this using document node:
```graphql
     """      nodes {
              name
              isEntry
              visibility
              return {
                signature
              }
    """
```
(lines omitted)

However I would like to create a DSL fragment but `return` fails Python (i.e. `Outer.return.select(...)`

Is there a way to inject a partial DocumentNode into a DocementNode generated from `dsl_gql`?

**Comment by leszekhanusz** [comment]
You could use `getattr(Outer, "return").select(...)` instead.

**Comment by FrankC01** [comment]
Works like a charm, exactley what I needed. 

Kudos!!!
