### ISSUE TITLE
Add retry logic to httpx Transport

### ISSUE THREAD

**Issue by mdlam92** [graphql-python/gql#470]
It would be dope if the httpx Transport had support for retry logic like the requests one does.

**Comment by leszekhanusz** [comment]
For which transport, the sync or async one? `HTTPXTransport` or `HTTPXAsyncTransport`?

**Comment by mdlam92** [comment]
I personally only use the synchronous one. But I'm sure folks would like support in both.

**Comment by leszekhanusz** [comment]
For async only:

- you can use [a permanent session](https://gql.readthedocs.io/en/stable/advanced/async_permanent_session.html) for which retries are enabled by default and can be configured.

For sync and async:

- use a [backoff](https://github.com/litl/backoff) decorator like shown [here](https://gql.readthedocs.io/en/stable/advanced/async_permanent_session.html#subscription-retries)

**Comment by mdlam92** [comment]
Oh nice, this is awesome. Exactly what I was looking for! Thanks :heart:
