### ISSUE TITLE
retry_execute can not handle TransportQueryError

### ISSUE THREAD

**Issue by PaleNeutron** [graphql-python/gql#472]
**Describe the bug**

See here, user defined `retry_execute`  wraps only `self._execute` .  I have a poor quality backend which will return error on random.

So I want to catch all exceptions include `TransportQueryError`. But current framework won't work.

https://github.com/graphql-python/gql/blob/48bb94cc4fc0755419c9edc7e8ef1470036c193d/gql/client.py#L1628-L1644

BTW, [current document](https://gql.readthedocs.io/en/stable/advanced/async_permanent_session.html#execution-retries) is a little misleading:

```python
# Here Only 3 tries for execute calls
retry_execute = backoff.on_exception(
    backoff.expo,
    Exception,
    max_tries=3,
    giveup=lambda e: isinstance(e, TransportQueryError),
)
session = await client.connect_async(
    reconnecting=True,
    retry_execute=retry_execute,
)
``` 

Users like me will believe remove giveup keyword will alllow it retry on `TransportQueryError`

**Comment by leszekhanusz** [comment]
You're right, the documentation is misleading. The `giveup` argument is not needed here.
It is only useful in the subscribe case below as it uses the outer method there.

I made some changes in  the documentation in PR #473 which should be clearer.
