### ISSUE TITLE
The calculation of time span is not correct

### ISSUE THREAD

**Issue by junluo-aspecta** [graphql-python/gql#482]
![image](https://github.com/graphql-python/gql/assets/127079652/a4c5ce77-c38a-4d4a-9258-8700e13960e7)
Intuitively,  the result of the first and second time period should be 0 cause the from and to are the same. And the last result will be 1 (which is the actually commit count of 2024-05-20) because the time span is just one day.

**Comment by leszekhanusz** [comment]
This issue does not seem to be related to gql.

**Comment by junluo-aspecta** [comment]
> This issue does not seem to be related to gql.

Isn't is the method to collect data of gql not correct?
