### ISSUE TITLE
Conflict in supported Python versions

### ISSUE THREAD

**Issue by Waitak** [graphql-python/gql#492]
- `README.md` says: This is a GraphQL client for Python **3.7+** (emphasis mine).
- `.github/workflows/tests.yml` says: python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "pypy3.8"]

The commit message says "[Remove Python 3.7 support](https://github.com/graphql-python/gql/commit/e63ed0faaae675143a494d7cff6e4b081dcd9d1b)". The two should agree.

**Comment by leszekhanusz** [comment]
All the current packages (both stable and pre-release) are supporting 3.7, and the 3.7 support has been dropped very recently in the master branch, so this is perfectly normal.

I'll change it on the README.md before making a new version.
