### ISSUE TITLE
requests transport keep alive

### ISSUE THREAD

**Issue by matt-pazien** [graphql-python/gql#53]
Is it possible for gql to have the RequestsHTTPTransport support session keep alive?  Requests uses the session object for keep-alive (https://requests.readthedocs.io/en/master/user/advanced/#session-objects).  

Is there any other suggested means for using keep alive in gql?

**Comment by matt-pazien** [comment]
I was able to essentially copy RequestsHTTPTransport and edit it so that it would use sessions.  Which is fine for now - but if the transport code in qgl changes I'll have to update my code.

**Comment by radekwlsk** [comment]
You could also create a Pull Request with your overwritten RequestsHTTPTransport. It is Open Source project, if you miss something in the library and implement it anyway on your own why not add it yourself to the core library?

**Comment by Cito** [comment]
Yes, please create a PR if you think it's useful for others as well.
