### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by codepoet80** [graphql-python/gql#54]
Tried replicating the two tests against a publicly available end-point, but they fail. Also tried lifting implementation ideas from Apollo documentation into Python, but the differences were not intuitively discoverable. Unable to proceed with any implementation.

**Comment by KingDarBoja** [comment]
Please take a look at [gql-next](https://github.com/graphql-python/gql-next) as it should be the next version of this library and it has better documentation.

Cheers!

**Comment by JayJeyaruban** [comment]
@KingDarBoja Is this still true? This lib seems to have far more recent commits than gql-next.

**Comment by KingDarBoja** [comment]
Kinda, the only difference besides the commit history is that `gql-next` has a better readme than `gql`. 

So better use `gql` as the current (and upcoming releases) version.

**Comment by Cito** [comment]
The plan is to eventually release `gql-next` as the next version of `gql`.

**Comment by KingDarBoja** [comment]
My latest PR should solve this issue as pointed out by #40.

It includes a [pytest example](https://github.com/graphql-python/gql/pull/60/commits/03f3f8d95e9f04e724584c01dbbb08280877d627) to fetch data from a public available endpoint.
