### ISSUE TITLE
Published?

### ISSUE THREAD

**Issue by chaffeqa** [graphql-python/gql#6]
```
pip install gql
Collecting gql
  Could not find a version that satisfies the requirement gql (from versions: )
No matching distribution found for gql
```

I would love this! Just started a really important company project using Apollo redux on the frontend.  Graphene seems like a great win, but would also love to be able to use gql!

**Comment by ekampf** [comment]
@chaffeqa you can install using `pip install git+git://github.com/graphql-python/gql.git`
I think @syrusakbary will publish the library once its interface relatively stable...

**Comment by syrusakbary** [comment]
I will publish it to PyPI soon @chaffeqa :)

**Comment by syrusakbary** [comment]
Just published it to PyPI.
https://pypi.python.org/pypi/gql
