### ISSUE TITLE
Query External Schema

### ISSUE THREAD

**Issue by redreceipt** [graphql-python/gql#64]
Is there a way to pass in a `schema.graphql` or `schema.json` file and query against that?

**Comment by KingDarBoja** [comment]
Please check this out: [README](https://github.com/graphql-python/gql/blob/2f44e403efbd0fa7a02b822f72646af4e767e6f1/README.md).

This comes from PR #63

**Comment by redreceipt** [comment]
Can't wait for that to go through. Big step globally as far as I can tell for Python GraphQL development. Good work!

**Comment by Cito** [comment]
The PR #63 is available now in v0.4.0.
