### ISSUE TITLE
how to upload file

### ISSUE THREAD

**Issue by DogeWatch** [graphql-python/gql#68]
Is there any example to show how to upload a file to the "Input!"?

**Comment by leahein** [comment]
I would love to know whether `gql` supports this, as well.

**Comment by leahein** [comment]
It doesn't look like this library currently supports files.  Is there any plan to support the [graphql multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec) in the future?

Happy to work on a PR for this as well.

**Comment by KingDarBoja** [comment]
@leahein the library doesn't support file uploads but there is a repo which implements that for Django and Flask servers, would be worth checking it: [graphene-file-upload](https://github.com/lmcgartland/graphene-file-upload).

**Comment by leahein** [comment]
> @leahein the library doesn't support file uploads but there is a repo which implements that for Django and Flask servers, would be worth checking it: [graphene-file-upload](https://github.com/lmcgartland/graphene-file-upload).

I was looking for file upload support for a python client that uses `graphene-file-upload` server-side.
I found [this one](https://pypi.org/project/aiogqlc/) that seems to support file upload well.

**Comment by KingDarBoja** [comment]
@leahein best idea would be a separated repo to support this feature as this would be a third party integration with `gql` library, hence making easier to maintain the core features as there aren't many contributors around here 🤔

**Comment by leszekhanusz** [comment]
Now that the aiohttp transport is implemented in #70 It should be relatively easy to incorporate the implementation from [aiogqlc](https://github.com/DoctorJohn/aiogqlc/blob/master/aiogqlc/client.py)

**Comment by leszekhanusz** [comment]
@leahein 
> Happy to work on a PR for this as well.

I think this would be a great addition to this library. I will accept your pull request in my own PR #70 if it comes with 100% test code coverage.

Note: to create temporary files in the tests, you can use [this method](https://stackoverflow.com/a/54053967/1221252)

**Comment by leszekhanusz** [comment]
@leahein 

Now that #70 has been merged, if you are still interested you should create your PR directly from the repo now.

**Comment by leahein** [comment]
@leszekhanusz Thanks for the details! I will work on adding file support 👍

**Comment by leszekhanusz** [comment]
@leahein did you make some progress on this ? I'll have some time in the following weeks so I will maybe start to implement this myself.

**Comment by leahein** [comment]
I did start on the feature [here](https://github.com/graphql-python/gql/compare/master...leahein:file-support?expand=1), but it's not complete. 
Right now there are `utils` to check whether a request contains files, and I started the transformation for sending them with the `requests` lib.

**Comment by KingDarBoja** [comment]
@leahein The link should be https://github.com/leahein/gql/tree/file-support :)

**Comment by sreerajkksd** [comment]
@leszekhanusz would you be able to implement this feature in a month or two ? I'm really looking forward to have this feature in this library.

**Comment by leszekhanusz** [comment]
This is now available in release v3.0.0a3. Tests and feedback is welcome.

**Comment by maaft** [comment]
Is file-upload support planned for sync transport? I cannot use async io in my application.

**Comment by leszekhanusz** [comment]
@maaft 
No, it is not planned. But you can use AIOHTTPTransport in a sync manner if you want.

**Comment by maaft** [comment]
The issue with AIOHTTPTransport is that it creates a new session everytime you execute a query/mutation. That sounds very inefficient and also I get random  "Transport is already connected" Exceptions from time to time. Might be some race conditions maybe.

**Comment by leszekhanusz** [comment]
> The issue with AIOHTTPTransport is that it creates a new session every time you execute a query/mutation. That sounds very inefficient 

Not necessarily, you can execute multiple queries and mutations on the same session (See [async usage](https://gql.readthedocs.io/en/v3.0.0a6/async/async_usage.html) and [async advanced usage](https://gql.readthedocs.io/en/v3.0.0a6/advanced/async_advanced_usage.html)). If you want to do it synchronously, it is still possible by running `loop.run_until_complete` yourself like in `Client::execute`

> and also I get random "Transport is already connected" Exceptions from time to time. Might be some race conditions maybe.

I suspect you try to execute queries from different threads or task with the same transport. If that is not the case, and if you can reproduce a minimal example, please submit an issue.

**Comment by maaft** [comment]
>I suspect you try to execute queries from different threads or task with the same transport. If that is not the case, and if you can reproduce a minimal example, please submit an issue.

Yes, that is indeed the case. I'm also thinking about rewriting all my code to make use of asyncio (instead of threads & processes) but unfortunately I rely on external libraries (pytorch in this case) that make heavy use of threads and processes already. And there is no way around using pytorch sadly. It's the defacto standard in machine learning. But who knows, maybe it will just fine with asyncio. I'll have to try.

**Comment by leszekhanusz** [comment]
See also #179 

And to be clear, it should be possible to support file uploads with the RequestsHTTPTransport. I'll accept a PR if it is well tested.

**Comment by leszekhanusz** [comment]
@maaft Could you please check if the PR #244 works well for you?

**Comment by maaft** [comment]
@leszekhanusz yes, it works. Thank you!
