### ISSUE TITLE
[feature] is there any plan for a cli?

### ISSUE THREAD

**Issue by shouldsee** [graphql-python/gql#69]

**Comment by KingDarBoja** [comment]
What do you mean by cli? Something like [gql-next](https://github.com/graphql-python/gql-next) perhaps?

**Comment by shouldsee** [comment]
I meant a command-line entry point that enables simpler integration with shells like bash.

**Comment by leszekhanusz** [comment]
Something [like this](https://github.com/graphql-python/gql/pull/70/commits/81b795064f06e4466ce30affea8465a86c3358b3) ?

The queries must be on one line and can be send with a pipe. Example:

```
$ echo 'query getContinents { continents {  code name } }' | python3.8 gql-cli.py wss://countries.trevorblades.com/graphql
{'continents': [{'code': 'AF', 'name': 'Africa'}, {'code': 'AN', 'name': 'Antarctica'}, {'code': 'AS', 'name': 'Asia'}, {'code': 'EU', 'name': 'Europe'}, {'code': 'NA', 'name': 'North America'}, {'code': 'OC', 'name': 'Oceania'}, {'code': 'SA', 'name': 'South America'}]}
```

**Comment by shouldsee** [comment]
@leszekhanusz Yes that's exactly what I was asking for! I am a bit new to websocket but I guess it would be good to support HTTP protocol as well?

**Comment by leszekhanusz** [comment]
@shouldsee For your information the http support is now implemented in gql-cli in the Pull request #70

**Comment by shouldsee** [comment]
Ahhh nice thanks!

**Comment by leszekhanusz** [comment]
It seems to work correctly for me with pyinstaller for Linux at least

**Comment by shouldsee** [comment]
nice!
