### ISSUE TITLE
Can you release a v0.5.0 ?

### ISSUE THREAD

**Issue by fclairamb** [graphql-python/gql#79]
Can you release a v0.5.0 of `gql`so that we can start using #73 in our tools? (possibly after merging #78).

**Comment by KingDarBoja** [comment]
@jkimbo @Cito are the ones active around here and they know how to release a new version. Of course both of them are busy with the other graphql projects so it will take a while to get released.

**Comment by Cito** [comment]
A quick v0.5.0 release with these patches is out now. Next step is to get v2 and v3 out, but I'm currently too busy for that.

**Comment by fclairamb** [comment]
Thank you very much !
