### ISSUE TITLE
Can't parse Shopify GraphQL schema

### ISSUE THREAD

**Issue by markhorgan** [graphql-python/gql#81]
I'm trying to use it with Shopify GraphQL Admin API but it can't parse the schema.

Single and multiline comments that use triple quotes:

```
"""Marks an element of a GraphQL schema as having restricted access."""
```

```
"""
Represents the access scope permission that is applicable to a merchant's shop, such as `read_orders`.

"""
```

Doesn't like null default value:

```
directive @accessRestricted(
  reason: String = null
) on FIELD_DEFINITION | OBJECT
```

Doesn't like union types:

```
type AppPurchaseOneTime implements AppPurchase & Node {
```

I'm using version 0.5.0

[schema.graphql.zip](https://github.com/graphql-python/gql/files/4623395/schema.graphql.zip)

**Comment by Cito** [comment]
We will soon switch to GraphQL-core v3 and then check if that already solves the issue.

**Comment by Cito** [comment]
@markhorgan gql 3.0.0a0 has been released now which uses GraphQL-core v3. Can you check that out?

**Comment by markhorgan** [comment]
It seems to work now! I tried it with a local schema and `fetch_schema_from_transport=True`
