### ISSUE TITLE
Document the "dsl" module/language

### ISSUE THREAD

**Issue by Cito** [graphql-python/gql#82]
The somewhat obscure "dsl" module/language included in gql should be documented. It is currently unclear to me where it is coming from, whether it mimics an existing thing or was an invention of @syrusakbary. Does anybody know?

Note: I'm not talking about the "schema definition language" of GraphQL here, but about the dsl module in gql. I think the name "dsl" is also a bit misleading because it usually means "domain specific language", but this is actually a general purpose language and not domain specific in the usual sense of "application domain specific". As far as I understand it is just an alternative way to express GraphQL documents in Python instead of JSON, Similar to the "SQL Expression language" in SQLAlchemy which allows writing SQL queries in Python.

**Comment by Cito** [comment]
Btw, there is also an "improved-dsl" feature branch that has not yet been merged if anybody wants to look into this.

**Comment by leszekhanusz** [comment]
FYI I added a very small example of the dsl module in the readme in PR #114

**Comment by leszekhanusz** [comment]
Note: I have completely refactored the DSL code in PR #169 
It is a breaking change but:
- it should integrate correctly with the rest of the current code (with sessions)
- it supports subscriptions
- and it comes with full documentation :tada:

I've looked into the improved-dsl branch and it sounds quite obsolete except maybe for the
"Add alias to selection as keyword argument" commit which could be a good idea to simplify the aliases?

**Comment by KingDarBoja** [comment]
> "Add alias to selection as keyword argument" commit which could be a good idea to simplify the aliases?

I am up for that change as well, maybe on same branch as refactored DSL 🤔

**Comment by leszekhanusz** [comment]
Fixed in v3.0.0a5
