### ISSUE TITLE
examples how to use "gql" method with mutations and variables ? 

### ISSUE THREAD

**Issue by arielvol** [graphql-python/gql#85]
Can someone show me an example how to use execute method with the "gql" option and with a mutation example which also needs variables ?

**Comment by KingDarBoja** [comment]
Hi @arielvol 

You can check out the readme and perform the same logic using the query example, like this (**taken from [test_query](https://github.com/graphql-python/gql/blob/v2.x/tests/starwars/test_query.py#L315))**:

```python
def test_mutation_result(client):
    query = gql(
        """
        mutation CreateReviewForEpisode($ep: Episode!, $review: ReviewInput!) {
          createReview(episode: $ep, review: $review) {
            stars
            commentary
          }
        }
    """
    )
    params = {
        "ep": "JEDI",
        "review": {"stars": 5, "commentary": "This is a great movie!"},
    }
    result = client.execute(query, variable_values=params)
```

**Comment by arielvol** [comment]
Great!!! thank you @KingDarBoja.

**Comment by Sultan91** [comment]
Still can't understand it(. `Episode` is it a type?, why do we need `"ep": "JEDI",`? 
An what if a mutation has no name, should it works like this: `mutation ($ep: Episode!, $review: ReviewInput!)`

**Comment by KingDarBoja** [comment]
`Episode` is a enum type, that's why you need to specify the value between `NEWHOPE`, `EMPIRE` or `JEDI` as you can seen at: https://github.com/graphql-python/gql/blob/master/tests/starwars/schema.py#L32
