### ISSUE TITLE
ModuleNotFoundError with the latest 0.5.0 version and the documentation example

### ISSUE THREAD

**Issue by int3l** [graphql-python/gql#88]
Reproduction:
```console
$ virtualenv env
$ . .\env\Scripts\activate
$ pip install aiohttp gql
$ python
>>> from gql.transport.aiohttp import AIOHTTPTransport
Traceback (most recent call last):
  File ".\test_gql.py", line 1, in <module>
    from gql.transport.aiohttp import AIOHTTPTransport
ModuleNotFoundError: No module named 'gql.transport.aiohttp'
```
Windows 10 1909
Python version 3.8.x
gql version 0.5.0 (latest available version in PyPI)

**Comment by int3l** [comment]
NVM, the docs on master require the latest dev version.

**Comment by Cito** [comment]
Yes, sorry for the confusion. New versions will be released tomorrow, including an alpha release with the new functionality.

**Comment by chelseatroy** [comment]
Hi! I'm having this exact same problem and I just installed gql today. Any ideas what's up?

**Comment by GraphtyLove** [comment]
Same here.

**Comment by lukasschmit** [comment]
Same!

**Comment by lightstrike** [comment]
The README was confusing for me - I got this running by specifying the alpha version, ie for `pipenv install gql[all]==3.0.0a6`

**Comment by MindaugasBernatavicius** [comment]
Same:

```
pip install aiohttp gql
```

```
from gql import gql, Client
from gql.transport.aiohttp import AIOHTTPTransport

# Select your transport with a defined url endpoint
transport = AIOHTTPTransport(url="https://countries.trevorblades.com/")

# Create a GraphQL client using the defined transport
client = Client(transport=transport, fetch_schema_from_transport=True)

# Provide a GraphQL query
query = gql(
    """
    query getContinents {
      continents {
        code
        name
      }
    }
"""
)

# Execute the query on the transport
result = client.execute(query)
print(result)
```

```
Traceback (most recent call last):
  File "C\..\rest_demo.py", line 2, in <module>
    from gql.transport.aiohttp import AIOHTTPTransport
ModuleNotFoundError: No module named 'gql.transport.aiohttp'
```

**Comment by leszekhanusz** [comment]
Please check the [installation instructions](https://gql.readthedocs.io/en/v3.0.0a6/intro.html#installation)

**Comment by roiweinreb** [comment]
Having the same issue. Tried it today.

**Comment by leszekhanusz** [comment]
Did you follow the installation instructions and used `pip install --pre gql[all]` ?

**Comment by roiweinreb** [comment]
@leszekhanusz it works, thanks!

**Comment by PaulApivat** [comment]
This worked for me:

`pip3 install 'gql[all]==3.0.0b0'`

- used quotes because my machine uses zsh instead of bash
- identifying most recent version of gql

**Comment by sarastinishi** [comment]
For those who still experiencing the same issue and using python poetry, you can use the following dependency spec in your `pyproject.toml`:
```
gql = {extras = ["all"], version = "~=3.0.0rc0", allow-prereleases = true}
```
