### ISSUE TITLE
After upgrading from v0.4.0 to v2.0.0 I get an exception

### ISSUE THREAD

**Issue by arielvol** [graphql-python/gql#90]
Hi,

I found out that I was on a very old version (v0.4.0) and upgraded to the latest steady release (v2.0.0) and simple queries that used to work not don't work and I get an exception:

Exception: {'message': "You cannot access body after reading from request's data stream"}

Did anyone encounter this ? what does this message mean ?

**Comment by leszekhanusz** [comment]
Hi,

Could you please post an example of query that you use so that we can see what parameters are used in the Client and in the transport ?

Did you use use_json=False in the RequestsHTTPTransport ?

**Comment by arielvol** [comment]
Hi @leszekhanusz 

This is my client config:
        try:
            self._transport = RequestsHTTPTransport(
                url=TITAN_SERVER,
                use_json=True,
                headers={
                    "content-type": "application/json",
                    "Authorization": f"Token {self._auth_token}",
                },
                verify=True,
               # retries=3
            )

            self._client = Client(
                 transport=self._transport, fetch_schema_from_transport=True
            )

and the query is :

 {
                 elementTypes {
                   name
                   id
                   description
                 }
               }


What is strange that if I change the  fetch_schema_from_transport to False, it starts to work
But why ? I also reverted back to 0.4.0 and it still doesn't work unless I turn of the " fetch_schema_from_transport" 

Any ideas what happened ? Maybe the upgrade to 2.0.0 did something ?

**Comment by leszekhanusz** [comment]
Are you sure you didn't change things on the server side ?
If you google the error, you find issues with django on the server side with the authorization middleware accessing request.body instead of request.data:
[See here](https://github.com/encode/django-rest-framework/issues/2774)

**Comment by arielvol** [comment]
We are using Django as the sever side with graphene, but I don't think the server was changed. 
I am working against playground server that as far as I know, nobody is changes the actual code there.
I read the link you sent but I still don't really understand what it means... :-(

**Comment by leszekhanusz** [comment]
Maybe it is because in 2.0.0, gql will use a session (the same tcp connection) for multiple requests and the server has a bug in this case.
Does the bug also appears when you try to execute the query twice (with fetch_schema_from_transport=False) ?

**Comment by arielvol** [comment]
Yes you are right @leszekhanusz.
whether the "fetch_schema_from_transport" is True or False, when I make a second request with another query I get the same exception.
The first query goes through but the second doesn't. This is strange cause now it also happens with the 0.4.0 version.

**Comment by leszekhanusz** [comment]
You could try to use the 3.0 alpha version.
With 3.0, if you run client.execute it will each time do it in another session.
Of course you cannot use `with Client(...) as session:` in your code

**Comment by arielvol** [comment]
Thank you @leszekhanusz 
I will try...

**Comment by KingDarBoja** [comment]
Hi @arielvol 

Have you solved your issue 😃  ?

**Comment by arielvol** [comment]
@KingDarBoja it depends what you call "solved" .
I upgraded to the new 3 beta version and that fixed the issues for me.... :-)

**Comment by KingDarBoja** [comment]
> @KingDarBoja it depends what you call "solved" .
> I upgraded to the new 3 beta version and that fixed the issues for me.... :-)

That's what I was asking for 🥳 
Closing this as resolved, if you have other issues with the new beta version, please let us know!
