### ISSUE TITLE
Is is possible to use an existing aiohttp session?

### ISSUE THREAD

**Issue by cglacet** [graphql-python/gql#91]
According to the documentation I should create a new session to make GraphQL requests using aiohttp, but imagine I have a provider that gives me both rest/graphql interfaces to its API, it would be nice to use a single session for both kinds of requests. Is that possible? 

I feel like changing [this](https://github.com/graphql-python/gql/blob/master/gql/transport/aiohttp.py#L55) would be enough, is that the case?

**Comment by leszekhanusz** [comment]
The aiohttp session is available in the transport when we are in a gql session.
Note that session here means two things: 
- the gql session which is an instance of `AsyncClientSession`
- the aiohttp session which is an instance of `aiohttp.ClientSession`

So you could reuse the session like this:

```python
async with Client(...) as session:

        # Execute graphql query on the  gql session
        result = await session.execute(query)

        # Execute POST query on the aiohttp session
        async with session.transport.session.post(YOUR REST REQUEST) as response:
            # manage the response here
```

Note that this would work only if you use  the `AIOHTTPTransport`, not the `WebsocketsTransport` so if you need subscriptions with websockets, you will need at least two sessions.

**Comment by cglacet** [comment]
So doing it the other way around isn't possible? (using an existing session as the session used by gql?). In my use case I can't really modify how the session is created therefore I can't create the session using gql. On the other hand I could very well have 2 sessions instead of one, but that seems a bit odd.

**Comment by leszekhanusz** [comment]
You could create your own transport class which inherits AIOHTTPTransport, set the session at init and modify connect and close calls to noop.

```python
class AIOHTTPTransportExistingSession(AIOHTTPTransport): 

    def __init__( ....., client_session: aiohttp.ClientSession):
        super().__init__(....)
        self.session = client_session

        async def connect(self) -> None:
            pass

        async def close(self) -> None:
            pass
```

**Comment by cglacet** [comment]
Ok, thanks, I'll test that solution :).

**Comment by leszekhanusz** [comment]
So did it work ? Closing this issue for now

**Comment by simion** [comment]
@leszekhanusz here's an example for Requests transport:

```python
class PersistentRequestsHTTPTransport(RequestsHTTPTransport):
    """
    In addition to RequestsHTTPTransport, this transport reuses requests.Session() between calls
    """

    def connect(self):
        if self.session is None:
            super().connect()

    def close(self):
        pass
```
