### ISSUE TITLE
Raised Exceptions are too generic, could we have a more specific one? 

### ISSUE THREAD

**Issue by stabacco** [graphql-python/gql#93]
There are a few places ([example](https://github.com/graphql-python/gql/blob/32c76afacb6d5539fc8d3f08ffe44f4ea167a128/gql/gql.py#L6)) where simple `Exception` s are being raised. 
Would it be possible to change those for some more specialized exceptions? Otherwise they are a bit difficult to catch and they could end up masking other errors.

Thanks.

**Comment by leszekhanusz** [comment]
In fact this specific check and exception could be removed and replaced by an annotation.

If the check is removed, then an exception of type `TypeError` should be generated from
[graphql/language/source.py#L29](https://github.com/graphql-python/graphql-core/blob/master/src/graphql/language/source.py#L29) (not tested)

I'll make a PR later.

**Comment by leszekhanusz** [comment]
I checked where are the other generic exception raised.

[client.py#L75](https://github.com/graphql-python/gql/blob/master/gql/client.py#L75) Could be replaced by an assertion
[dsl.py#L127](https://github.com/graphql-python/gql/blob/master/gql/dsl.py#L127) Could be replaced by a TypeError
[scripts/gql-cli#L30](https://github.com/graphql-python/gql/blob/master/scripts/gql-cli#L30) Could be replaced by a ValueError

**Comment by leszekhanusz** [comment]
Now Implemented in PR #95

**Comment by KingDarBoja** [comment]
Closing as resolved by #95.
